//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
// <auto-generated />
using System.Text.Json;
using System.Text.Json.Serialization;
using Apigen.Keycloak.Admin.Models;

#nullable enable

namespace Apigen.Keycloak.Admin.Client;

/// <summary>
/// Internal JSON serialization configuration.
/// </summary>
internal static class JsonConfig
{
  /// <summary>
  /// Default JSON serializer options for all API operations.
  /// </summary>
  internal static readonly JsonSerializerOptions Default = CreateOptions();

  private static JsonSerializerOptions CreateOptions()
  {
    JsonSerializerOptions options = new()
    {
      DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };
    options.Converters.Add(new SmartEnumConverterFactory());
    return options;
  }
}
