//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Keycloak.Admin.Models;

#nullable enable

namespace Apigen.Keycloak.Admin.Client;

/// <summary>
/// Interface for Attack Detection operations
/// </summary>
public partial interface IAttackDetectionClient
{
  /// <summary>
  /// Clear any user login failures for all users This can release temporary disabled users
  /// Operation: DELETE /admin/realms/{realm}/attack-detection/brute-force/users
  /// </summary>
  Task DeleteAsync(string realm, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get status of a username in brute force detection
  /// Operation: GET /admin/realms/{realm}/attack-detection/brute-force/users/{userId}
  /// </summary>
  Task<JsonElement> GetAsync(string userId, string realm, CancellationToken cancellationToken = default);

  /// <summary>
  /// Clear any user login failures for the user This can release temporary disabled user
  /// Operation: DELETE /admin/realms/{realm}/attack-detection/brute-force/users/{userId}
  /// </summary>
  Task DeleteAsync(string userId, string realm, CancellationToken cancellationToken = default);

}
