//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Keycloak.Admin.Models;

#nullable enable

namespace Apigen.Keycloak.Admin.Client;

/// <summary>
/// Interface for Client Initial Access operations
/// </summary>
public partial interface IClientInitialAccessClient
{
  /// <summary>
  /// 
  /// Operation: GET /admin/realms/{realm}/clients-initial-access
  /// </summary>
  Task<List<ClientInitialAccessPresentation>> GetAsync(string realm, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a new initial access token.
  /// Operation: POST /admin/realms/{realm}/clients-initial-access
  /// </summary>
  Task<ClientInitialAccessCreatePresentation> PostAsync(string realm, Apigen.Keycloak.Admin.Models.ClientInitialAccessCreatePresentation clientInitialAccessCreatePresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// 
  /// Operation: DELETE /admin/realms/{realm}/clients-initial-access/{id}
  /// </summary>
  Task DeleteAsync(string id, string realm, CancellationToken cancellationToken = default);

}
