//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Keycloak.Admin.Models;

#nullable enable

namespace Apigen.Keycloak.Admin.Client;

/// <summary>
/// Interface for Client Scopes operations
/// </summary>
public partial interface IClientScopesClient
{
  /// <summary>
  /// Get client scopes belonging to the realm Returns a list of client scopes belonging to the realm
  /// Operation: GET /admin/realms/{realm}/client-scopes
  /// </summary>
  Task<List<ClientScopeRepresentation>> GetAsync(string realm, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a new client scope Client Scope’s name must be unique!
  /// Operation: POST /admin/realms/{realm}/client-scopes
  /// </summary>
  Task PostAsync(string realm, Apigen.Keycloak.Admin.Models.ClientScopeRepresentation clientScopeRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get representation of the client scope
  /// Operation: GET /admin/realms/{realm}/client-scopes/{client-scope-id}
  /// </summary>
  Task<ClientScopeRepresentation> GetAsync(string realm, string clientScopeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update the client scope
  /// Operation: PUT /admin/realms/{realm}/client-scopes/{client-scope-id}
  /// </summary>
  Task PutAsync(string realm, string clientScopeId, Apigen.Keycloak.Admin.Models.ClientScopeRepresentation clientScopeRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete the client scope
  /// Operation: DELETE /admin/realms/{realm}/client-scopes/{client-scope-id}
  /// </summary>
  Task DeleteAsync(string realm, string clientScopeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get client scopes belonging to the realm Returns a list of client scopes belonging to the realm
  /// Operation: GET /admin/realms/{realm}/client-templates
  /// </summary>
  Task<List<ClientScopeRepresentation>> GetAdminRealmsClientTemplatesAsync(string realm, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a new client scope Client Scope’s name must be unique!
  /// Operation: POST /admin/realms/{realm}/client-templates
  /// </summary>
  Task PostAdminRealmsClientTemplatesAsync(string realm, Apigen.Keycloak.Admin.Models.ClientScopeRepresentation clientScopeRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get representation of the client scope
  /// Operation: GET /admin/realms/{realm}/client-templates/{client-scope-id}
  /// </summary>
  Task<ClientScopeRepresentation> GetAdminRealmsClientTemplatesAsync(string realm, string clientScopeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update the client scope
  /// Operation: PUT /admin/realms/{realm}/client-templates/{client-scope-id}
  /// </summary>
  Task UpdateAdminRealmsClientTemplatesAsync(string realm, string clientScopeId, Apigen.Keycloak.Admin.Models.ClientScopeRepresentation clientScopeRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete the client scope
  /// Operation: DELETE /admin/realms/{realm}/client-templates/{client-scope-id}
  /// </summary>
  Task DeleteAdminRealmsClientTemplatesAsync(string realm, string clientScopeId, CancellationToken cancellationToken = default);

}
