//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Keycloak.Admin.Models;

#nullable enable

namespace Apigen.Keycloak.Admin.Client;

/// <summary>
/// Interface for Client Role Mappings operations
/// </summary>
public partial interface IClientRoleMappingsClient
{
  /// <summary>
  /// Get client-level role mappings for the user or group, and the app
  /// Operation: GET /admin/realms/{realm}/groups/{group-id}/role-mappings/clients/{client-id}
  /// </summary>
  Task<List<RoleRepresentation>> GetAsync(string realm, string groupId, string clientId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Add client-level roles to the user or group role mapping
  /// Operation: POST /admin/realms/{realm}/groups/{group-id}/role-mappings/clients/{client-id}
  /// </summary>
  Task PostAsync(string realm, string groupId, string clientId, List<RoleRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete client-level roles from user or group role mapping
  /// Operation: DELETE /admin/realms/{realm}/groups/{group-id}/role-mappings/clients/{client-id}
  /// </summary>
  Task DeleteAsync(string realm, string groupId, string clientId, List<RoleRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get available client-level roles that can be mapped to the user or group
  /// Operation: GET /admin/realms/{realm}/groups/{group-id}/role-mappings/clients/{client-id}/available
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsGroupsRoleMappingsClientsAvailableAsync(string realm, string groupId, string clientId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get effective client-level role mappings This recurses any composite roles
  /// Operation: GET /admin/realms/{realm}/groups/{group-id}/role-mappings/clients/{client-id}/composite
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsGroupsRoleMappingsClientsCompositeAsync(string realm, string groupId, string clientId, GetClientRoleMappingsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get client-level role mappings for the user or group, and the app
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/role-mappings/clients/{client-id}
  /// </summary>
  Task<List<RoleRepresentation>> GetAsync(string realm, string orgId, string groupId, string clientId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Add client-level roles to the user or group role mapping
  /// Operation: POST /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/role-mappings/clients/{client-id}
  /// </summary>
  Task PostAsync(string realm, string orgId, string groupId, string clientId, List<RoleRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete client-level roles from user or group role mapping
  /// Operation: DELETE /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/role-mappings/clients/{client-id}
  /// </summary>
  Task DeleteAsync(string realm, string orgId, string groupId, string clientId, List<RoleRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get available client-level roles that can be mapped to the user or group
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/role-mappings/clients/{client-id}/available
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsOrganizationsGroupsRoleMappingsClientsAvailableAsync(string realm, string orgId, string groupId, string clientId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get effective client-level role mappings This recurses any composite roles
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/role-mappings/clients/{client-id}/composite
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsOrganizationsGroupsRoleMappingsClientsCompositeAsync(string realm, string orgId, string groupId, string clientId, GetClientRoleMappingsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get client-level role mappings for the user or group, and the app
  /// Operation: GET /admin/realms/{realm}/users/{user-id}/role-mappings/clients/{client-id}
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsUsersRoleMappingsClientsAsync(string realm, string userId, string clientId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Add client-level roles to the user or group role mapping
  /// Operation: POST /admin/realms/{realm}/users/{user-id}/role-mappings/clients/{client-id}
  /// </summary>
  Task PostAdminRealmsUsersRoleMappingsClientsAsync(string realm, string userId, string clientId, List<RoleRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete client-level roles from user or group role mapping
  /// Operation: DELETE /admin/realms/{realm}/users/{user-id}/role-mappings/clients/{client-id}
  /// </summary>
  Task DeleteAdminRealmsUsersRoleMappingsClientsAsync(string realm, string userId, string clientId, List<RoleRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get available client-level roles that can be mapped to the user or group
  /// Operation: GET /admin/realms/{realm}/users/{user-id}/role-mappings/clients/{client-id}/available
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsUsersRoleMappingsClientsAvailableAsync(string realm, string userId, string clientId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get effective client-level role mappings This recurses any composite roles
  /// Operation: GET /admin/realms/{realm}/users/{user-id}/role-mappings/clients/{client-id}/composite
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsUsersRoleMappingsClientsCompositeAsync(string realm, string userId, string clientId, GetClientRoleMappingsRequest? request = null, CancellationToken cancellationToken = default);

}
