//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Keycloak.Admin.Models;

#nullable enable

namespace Apigen.Keycloak.Admin.Client;

/// <summary>
/// Interface for Key operations
/// </summary>
public partial interface IKeyClient
{
  /// <summary>
  /// 
  /// Operation: GET /admin/realms/{realm}/keys
  /// </summary>
  Task<KeysMetadataRepresentation> GetAsync(string realm, CancellationToken cancellationToken = default);

}
