//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Keycloak.Admin.Models;

#nullable enable

namespace Apigen.Keycloak.Admin.Client;

/// <summary>
/// Interface for Organizations operations
/// </summary>
public partial interface IOrganizationsClient
{
  /// <summary>
  /// Returns a paginated list of organizations filtered according to the specified parameters
  /// Operation: GET /admin/realms/{realm}/organizations
  /// </summary>
  Task<List<OrganizationRepresentation>> GetAsync(string realm, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Creates a new organization
  /// Operation: POST /admin/realms/{realm}/organizations
  /// </summary>
  Task PostAsync(string realm, Apigen.Keycloak.Admin.Models.OrganizationRepresentation organizationRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns the organizations counts.
  /// Operation: GET /admin/realms/{realm}/organizations/count
  /// </summary>
  Task<long> GetAdminRealmsOrganizationsCountAsync(string realm, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns the organizations associated with the user that has the specified id
  /// Operation: GET /admin/realms/{realm}/organizations/members/{member-id}/organizations
  /// </summary>
  Task<List<OrganizationRepresentation>> GetAsync(string memberId, string realm, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns the organization representation
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}
  /// </summary>
  Task<OrganizationRepresentation> GetAdminRealmsOrganizationsAsync(string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Updates the organization
  /// Operation: PUT /admin/realms/{realm}/organizations/{org-id}
  /// </summary>
  Task UpdateAsync(string realm, string orgId, Apigen.Keycloak.Admin.Models.OrganizationRepresentation organizationRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Deletes the organization
  /// Operation: DELETE /admin/realms/{realm}/organizations/{org-id}
  /// </summary>
  Task DeleteAsync(string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get organization groups
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/groups
  /// </summary>
  Task<List<GroupRepresentation>> GetAdminRealmsOrganizationsGroupsAsync(string realm, string orgId, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Creates a new top-level group or moves an existing group to top-level
  /// Operation: POST /admin/realms/{realm}/organizations/{org-id}/groups
  /// </summary>
  Task PostAsync(string realm, string orgId, Apigen.Keycloak.Admin.Models.GroupRepresentation groupRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get organization group by path
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/groups/group-by-path/{path}
  /// </summary>
  Task<GroupRepresentation> GetAsync(string path, string realm, string orgId, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get organization group representation
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}
  /// </summary>
  Task<GroupRepresentation> GetAdminRealmsOrganizationsGroupsAsync(string realm, string orgId, string groupId, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update organization group
  /// Operation: PUT /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}
  /// </summary>
  Task PutAsync(string realm, string orgId, string groupId, Apigen.Keycloak.Admin.Models.GroupRepresentation groupRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete the organization group
  /// Operation: DELETE /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}
  /// </summary>
  Task DeleteAsync(string realm, string orgId, string groupId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get subgroups of this organization group
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/children
  /// </summary>
  Task<List<GroupRepresentation>> GetAdminRealmsOrganizationsGroupsChildrenAsync(string realm, string orgId, string groupId, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create or move a subgroup
  /// Operation: POST /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/children
  /// </summary>
  Task PostAsync(string realm, string orgId, string groupId, Apigen.Keycloak.Admin.Models.GroupRepresentation groupRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get members of this organization group
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/members
  /// </summary>
  Task<List<MemberRepresentation>> GetAdminRealmsOrganizationsGroupsMembersAsync(string realm, string orgId, string groupId, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Add a user to this organization group
  /// Operation: PUT /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/members/{userId}
  /// </summary>
  Task PutAsync(string userId, string realm, string orgId, string groupId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Remove a user from this organization group
  /// Operation: DELETE /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/members/{userId}
  /// </summary>
  Task DeleteAsync(string userId, string realm, string orgId, string groupId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns all identity providers associated with the organization
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/identity-providers
  /// </summary>
  Task<List<IdentityProviderRepresentation>> GetAdminRealmsOrganizationsIdentityProvidersAsync(string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Adds the identity provider with the specified id to the organization
  /// Operation: POST /admin/realms/{realm}/organizations/{org-id}/identity-providers
  /// </summary>
  Task PostAsync(string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns the identity provider associated with the organization that has the specified alias
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/identity-providers/{alias}
  /// </summary>
  Task<IdentityProviderRepresentation> GetAdminRealmsOrganizationsIdentityProvidersAsync(string alias, string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Removes the identity provider with the specified alias from the organization
  /// Operation: DELETE /admin/realms/{realm}/organizations/{org-id}/identity-providers/{alias}
  /// </summary>
  Task DeleteAdminRealmsOrganizationsIdentityProvidersAsync(string alias, string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns organization groups for the identity provider
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/identity-providers/{alias}/groups
  /// </summary>
  Task<List<GroupRepresentation>> GetAdminRealmsOrganizationsIdentityProvidersGroupsAsync(string alias, string realm, string orgId, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get invitations for the organization
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/invitations
  /// </summary>
  Task<List<OrganizationInvitationRepresentation>> GetAdminRealmsOrganizationsInvitationsAsync(string realm, string orgId, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get invitation by ID
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/invitations/{id}
  /// </summary>
  Task<OrganizationInvitationRepresentation> GetAdminRealmsOrganizationsInvitationsAsync(string id, string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete an invitation
  /// Operation: DELETE /admin/realms/{realm}/organizations/{org-id}/invitations/{id}
  /// </summary>
  Task DeleteAdminRealmsOrganizationsInvitationsAsync(string id, string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Resend an invitation
  /// Operation: POST /admin/realms/{realm}/organizations/{org-id}/invitations/{id}/resend
  /// </summary>
  Task PostAsync(string id, string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns a paginated list of organization members filtered according to the specified parameters
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/members
  /// </summary>
  Task<List<MemberRepresentation>> GetAdminRealmsOrganizationsMembersAsync(string realm, string orgId, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Adds the user with the specified id as a member of the organization
  /// Operation: POST /admin/realms/{realm}/organizations/{org-id}/members
  /// </summary>
  Task PostAdminRealmsOrganizationsMembersAsync(string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns number of members in the organization.
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/members/count
  /// </summary>
  Task<long> GetAdminRealmsOrganizationsMembersCountAsync(string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Invites an existing user to the organization, using the specified user id
  /// Operation: POST /admin/realms/{realm}/organizations/{org-id}/members/invite-existing-user
  /// </summary>
  Task PostAdminRealmsOrganizationsMembersInviteExistingUserAsync(string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Invites an existing user or sends a registration link to a new user, based on the provided e-mail address.
  /// Operation: POST /admin/realms/{realm}/organizations/{org-id}/members/invite-user
  /// </summary>
  Task PostAdminRealmsOrganizationsMembersInviteUserAsync(string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns the member of the organization with the specified id
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/members/{member-id}
  /// </summary>
  Task<MemberRepresentation> GetAdminRealmsOrganizationsMembersAsync(string memberId, string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Removes the user with the specified id from the organization
  /// Operation: DELETE /admin/realms/{realm}/organizations/{org-id}/members/{member-id}
  /// </summary>
  Task DeleteAdminRealmsOrganizationsMembersAsync(string memberId, string realm, string orgId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns the organization group memberships for a member with the specified id
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/members/{member-id}/groups
  /// </summary>
  Task<List<GroupRepresentation>> GetAdminRealmsOrganizationsMembersGroupsAsync(string memberId, string realm, string orgId, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Returns the organizations associated with the user that has the specified id
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/members/{member-id}/organizations
  /// </summary>
  Task<List<OrganizationRepresentation>> GetAdminRealmsOrganizationsMembersOrganizationsAsync(string memberId, string realm, string orgId, GetOrganizationsRequest? request = null, CancellationToken cancellationToken = default);

}
