//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Keycloak.Admin.Models;

#nullable enable

namespace Apigen.Keycloak.Admin.Client;

/// <summary>
/// Interface for Protocol Mappers operations
/// </summary>
public partial interface IProtocolMappersClient
{
  /// <summary>
  /// Create multiple mappers
  /// Operation: POST /admin/realms/{realm}/client-scopes/{client-scope-id}/protocol-mappers/add-models
  /// </summary>
  Task PostAsync(string realm, string clientScopeId, List<ProtocolMapperRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get mappers
  /// Operation: GET /admin/realms/{realm}/client-scopes/{client-scope-id}/protocol-mappers/models
  /// </summary>
  Task<List<ProtocolMapperRepresentation>> GetAsync(string realm, string clientScopeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a mapper
  /// Operation: POST /admin/realms/{realm}/client-scopes/{client-scope-id}/protocol-mappers/models
  /// </summary>
  Task PostAsync(string realm, string clientScopeId, Apigen.Keycloak.Admin.Models.ProtocolMapperRepresentation protocolMapperRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get mapper by id
  /// Operation: GET /admin/realms/{realm}/client-scopes/{client-scope-id}/protocol-mappers/models/{id}
  /// </summary>
  Task<ProtocolMapperRepresentation> GetAsync(string id, string realm, string clientScopeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update the mapper
  /// Operation: PUT /admin/realms/{realm}/client-scopes/{client-scope-id}/protocol-mappers/models/{id}
  /// </summary>
  Task PutAsync(string id, string realm, string clientScopeId, Apigen.Keycloak.Admin.Models.ProtocolMapperRepresentation protocolMapperRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete the mapper
  /// Operation: DELETE /admin/realms/{realm}/client-scopes/{client-scope-id}/protocol-mappers/models/{id}
  /// </summary>
  Task DeleteAsync(string id, string realm, string clientScopeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get mappers by name for a specific protocol
  /// Operation: GET /admin/realms/{realm}/client-scopes/{client-scope-id}/protocol-mappers/protocol/{protocol}
  /// </summary>
  Task<List<ProtocolMapperRepresentation>> GetAdminRealmsClientScopesProtocolMappersProtocolAsync(string protocol, string realm, string clientScopeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create multiple mappers
  /// Operation: POST /admin/realms/{realm}/client-templates/{client-scope-id}/protocol-mappers/add-models
  /// </summary>
  Task PostAdminRealmsClientTemplatesProtocolMappersAddModelsAsync(string realm, string clientScopeId, List<ProtocolMapperRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get mappers
  /// Operation: GET /admin/realms/{realm}/client-templates/{client-scope-id}/protocol-mappers/models
  /// </summary>
  Task<List<ProtocolMapperRepresentation>> GetAdminRealmsClientTemplatesProtocolMappersModelsAsync(string realm, string clientScopeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a mapper
  /// Operation: POST /admin/realms/{realm}/client-templates/{client-scope-id}/protocol-mappers/models
  /// </summary>
  Task PostAdminRealmsClientTemplatesProtocolMappersModelsAsync(string realm, string clientScopeId, Apigen.Keycloak.Admin.Models.ProtocolMapperRepresentation protocolMapperRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get mapper by id
  /// Operation: GET /admin/realms/{realm}/client-templates/{client-scope-id}/protocol-mappers/models/{id}
  /// </summary>
  Task<ProtocolMapperRepresentation> GetAdminRealmsClientTemplatesProtocolMappersModelsAsync(string id, string realm, string clientScopeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update the mapper
  /// Operation: PUT /admin/realms/{realm}/client-templates/{client-scope-id}/protocol-mappers/models/{id}
  /// </summary>
  Task UpdateAdminRealmsClientTemplatesProtocolMappersModelsAsync(string id, string realm, string clientScopeId, Apigen.Keycloak.Admin.Models.ProtocolMapperRepresentation protocolMapperRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete the mapper
  /// Operation: DELETE /admin/realms/{realm}/client-templates/{client-scope-id}/protocol-mappers/models/{id}
  /// </summary>
  Task DeleteAdminRealmsClientTemplatesProtocolMappersModelsAsync(string id, string realm, string clientScopeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get mappers by name for a specific protocol
  /// Operation: GET /admin/realms/{realm}/client-templates/{client-scope-id}/protocol-mappers/protocol/{protocol}
  /// </summary>
  Task<List<ProtocolMapperRepresentation>> GetAdminRealmsClientTemplatesProtocolMappersProtocolAsync(string protocol, string realm, string clientScopeId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create multiple mappers
  /// Operation: POST /admin/realms/{realm}/clients/{client-uuid}/protocol-mappers/add-models
  /// </summary>
  Task PostAdminRealmsClientsProtocolMappersAddModelsAsync(string realm, string clientUuid, List<ProtocolMapperRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get mappers
  /// Operation: GET /admin/realms/{realm}/clients/{client-uuid}/protocol-mappers/models
  /// </summary>
  Task<List<ProtocolMapperRepresentation>> GetAdminRealmsClientsProtocolMappersModelsAsync(string realm, string clientUuid, CancellationToken cancellationToken = default);

  /// <summary>
  /// Create a mapper
  /// Operation: POST /admin/realms/{realm}/clients/{client-uuid}/protocol-mappers/models
  /// </summary>
  Task PostAdminRealmsClientsProtocolMappersModelsAsync(string realm, string clientUuid, Apigen.Keycloak.Admin.Models.ProtocolMapperRepresentation protocolMapperRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get mapper by id
  /// Operation: GET /admin/realms/{realm}/clients/{client-uuid}/protocol-mappers/models/{id}
  /// </summary>
  Task<ProtocolMapperRepresentation> GetAdminRealmsClientsProtocolMappersModelsAsync(string id, string realm, string clientUuid, CancellationToken cancellationToken = default);

  /// <summary>
  /// Update the mapper
  /// Operation: PUT /admin/realms/{realm}/clients/{client-uuid}/protocol-mappers/models/{id}
  /// </summary>
  Task UpdateAdminRealmsClientsProtocolMappersModelsAsync(string id, string realm, string clientUuid, Apigen.Keycloak.Admin.Models.ProtocolMapperRepresentation protocolMapperRepresentation, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete the mapper
  /// Operation: DELETE /admin/realms/{realm}/clients/{client-uuid}/protocol-mappers/models/{id}
  /// </summary>
  Task DeleteAdminRealmsClientsProtocolMappersModelsAsync(string id, string realm, string clientUuid, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get mappers by name for a specific protocol
  /// Operation: GET /admin/realms/{realm}/clients/{client-uuid}/protocol-mappers/protocol/{protocol}
  /// </summary>
  Task<List<ProtocolMapperRepresentation>> GetAdminRealmsClientsProtocolMappersProtocolAsync(string protocol, string realm, string clientUuid, CancellationToken cancellationToken = default);

}
