//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Apigen.Keycloak.Admin.Models;

#nullable enable

namespace Apigen.Keycloak.Admin.Client;

/// <summary>
/// Interface for Role Mapper operations
/// </summary>
public partial interface IRoleMapperClient
{
  /// <summary>
  /// Get role mappings
  /// Operation: GET /admin/realms/{realm}/groups/{group-id}/role-mappings
  /// </summary>
  Task<MappingsRepresentation> GetAsync(string realm, string groupId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get realm-level role mappings
  /// Operation: GET /admin/realms/{realm}/groups/{group-id}/role-mappings/realm
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsGroupsRoleMappingsRealmAsync(string realm, string groupId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Add realm-level role mappings to the user
  /// Operation: POST /admin/realms/{realm}/groups/{group-id}/role-mappings/realm
  /// </summary>
  Task PostAsync(string realm, string groupId, List<RoleRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete realm-level role mappings
  /// Operation: DELETE /admin/realms/{realm}/groups/{group-id}/role-mappings/realm
  /// </summary>
  Task DeleteAsync(string realm, string groupId, List<RoleRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get realm-level roles that can be mapped
  /// Operation: GET /admin/realms/{realm}/groups/{group-id}/role-mappings/realm/available
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsGroupsRoleMappingsRealmAvailableAsync(string realm, string groupId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get effective realm-level role mappings This will recurse all composite roles to get the result.
  /// Operation: GET /admin/realms/{realm}/groups/{group-id}/role-mappings/realm/composite
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsGroupsRoleMappingsRealmCompositeAsync(string realm, string groupId, GetRoleMapperRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get role mappings
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/role-mappings
  /// </summary>
  Task<MappingsRepresentation> GetAsync(string realm, string orgId, string groupId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get realm-level role mappings
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/role-mappings/realm
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsOrganizationsGroupsRoleMappingsRealmAsync(string realm, string orgId, string groupId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Add realm-level role mappings to the user
  /// Operation: POST /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/role-mappings/realm
  /// </summary>
  Task PostAsync(string realm, string orgId, string groupId, List<RoleRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete realm-level role mappings
  /// Operation: DELETE /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/role-mappings/realm
  /// </summary>
  Task DeleteAsync(string realm, string orgId, string groupId, List<RoleRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get realm-level roles that can be mapped
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/role-mappings/realm/available
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsOrganizationsGroupsRoleMappingsRealmAvailableAsync(string realm, string orgId, string groupId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get effective realm-level role mappings This will recurse all composite roles to get the result.
  /// Operation: GET /admin/realms/{realm}/organizations/{org-id}/groups/{group-id}/role-mappings/realm/composite
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsOrganizationsGroupsRoleMappingsRealmCompositeAsync(string realm, string orgId, string groupId, GetRoleMapperRequest? request = null, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get role mappings
  /// Operation: GET /admin/realms/{realm}/users/{user-id}/role-mappings
  /// </summary>
  Task<MappingsRepresentation> GetAdminRealmsUsersRoleMappingsAsync(string realm, string userId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get realm-level role mappings
  /// Operation: GET /admin/realms/{realm}/users/{user-id}/role-mappings/realm
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsUsersRoleMappingsRealmAsync(string realm, string userId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Add realm-level role mappings to the user
  /// Operation: POST /admin/realms/{realm}/users/{user-id}/role-mappings/realm
  /// </summary>
  Task PostAdminRealmsUsersRoleMappingsRealmAsync(string realm, string userId, List<RoleRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Delete realm-level role mappings
  /// Operation: DELETE /admin/realms/{realm}/users/{user-id}/role-mappings/realm
  /// </summary>
  Task DeleteAdminRealmsUsersRoleMappingsRealmAsync(string realm, string userId, List<RoleRepresentation> body, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get realm-level roles that can be mapped
  /// Operation: GET /admin/realms/{realm}/users/{user-id}/role-mappings/realm/available
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsUsersRoleMappingsRealmAvailableAsync(string realm, string userId, CancellationToken cancellationToken = default);

  /// <summary>
  /// Get effective realm-level role mappings This will recurse all composite roles to get the result.
  /// Operation: GET /admin/realms/{realm}/users/{user-id}/role-mappings/realm/composite
  /// </summary>
  Task<List<RoleRepresentation>> GetAdminRealmsUsersRoleMappingsRealmCompositeAsync(string realm, string userId, GetRoleMapperRequest? request = null, CancellationToken cancellationToken = default);

}
