//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// AccessToken from OpenAPI schema.
/// Schema path: #/components/schemas/AccessToken
/// </summary>
public class AccessToken
{
  [System.Text.Json.Serialization.JsonPropertyName("jti")]
  public string? Jti { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("exp")]
  public long? Exp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("nbf")]
  public long? Nbf { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("iat")]
  public long? Iat { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("iss")]
  public string? Iss { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("sub")]
  public string? Sub { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("typ")]
  public string? Typ { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("azp")]
  public string? Azp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("otherClaims")]
  public Dictionary<string, object?>? OtherClaims { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("nonce")]
  public string? Nonce { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("auth_time")]
  public long? AuthTime { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("sid")]
  public string? Sid { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("at_hash")]
  public string? AtHash { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("c_hash")]
  public string? CHash { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("given_name")]
  public string? GivenName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("family_name")]
  public string? FamilyName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("middle_name")]
  public string? MiddleName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("nickname")]
  public string? Nickname { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("preferred_username")]
  public string? PreferredUsername { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("profile")]
  public string? Profile { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("picture")]
  public string? Picture { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("website")]
  public string? Website { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email_verified")]
  public bool? EmailVerified { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("gender")]
  public string? Gender { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("birthdate")]
  public string? Birthdate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("zoneinfo")]
  public string? Zoneinfo { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("locale")]
  public string? Locale { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("phone_number")]
  public string? PhoneNumber { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("phone_number_verified")]
  public bool? PhoneNumberVerified { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
  public long? UpdatedAt { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("claims_locales")]
  public string? ClaimsLocales { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("acr")]
  public string? Acr { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("s_hash")]
  public string? SHash { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("trusted-certs")]
  public List<string?>? TrustedCerts { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("allowed-origins")]
  public List<string?>? AllowedOrigins { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("realm_access")]
  public Access? RealmAccess { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resource_access")]
  public Dictionary<string, Access>? ResourceAccess { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authorization")]
  public Authorization? Authorization { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cnf")]
  public Confirmation? Cnf { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("scope")]
  public string? Scope { get; set; }
}
