//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// AdminEventRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/AdminEventRepresentation
/// </summary>
public class AdminEventRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("time")]
  public long? Time { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("realmId")]
  public string? RealmId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authDetails")]
  public AuthDetailsRepresentation? AuthDetails { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("operationType")]
  public string? OperationType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resourceType")]
  public string? ResourceType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resourcePath")]
  public string? ResourcePath { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("representation")]
  public string? Representation { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("error")]
  public string? Error { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("details")]
  public Dictionary<string, string?>? Details { get; set; }
}
