//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// ApplicationRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/ApplicationRepresentation
/// </summary>
public class ApplicationRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientId")]
  public string? ClientId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rootUrl")]
  public string? RootUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("adminUrl")]
  public string? AdminUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("baseUrl")]
  public string? BaseUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("surrogateAuthRequired")]
  public bool? SurrogateAuthRequired { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("alwaysDisplayInConsole")]
  public bool? AlwaysDisplayInConsole { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientAuthenticatorType")]
  public string? ClientAuthenticatorType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("secret")]
  public string? Secret { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("registrationAccessToken")]
  public string? RegistrationAccessToken { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("defaultRoles")]
  public List<string?>? DefaultRoles { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("redirectUris")]
  public List<string?>? RedirectUris { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webOrigins")]
  public List<string?>? WebOrigins { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("notBefore")]
  public int? NotBefore { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("bearerOnly")]
  public bool? BearerOnly { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("consentRequired")]
  public bool? ConsentRequired { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("standardFlowEnabled")]
  public bool? StandardFlowEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("implicitFlowEnabled")]
  public bool? ImplicitFlowEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("directAccessGrantsEnabled")]
  public bool? DirectAccessGrantsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("serviceAccountsEnabled")]
  public bool? ServiceAccountsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authorizationServicesEnabled")]
  public bool? AuthorizationServicesEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("directGrantsOnly")]
  public bool? DirectGrantsOnly { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("publicClient")]
  public bool? PublicClient { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("frontchannelLogout")]
  public bool? FrontchannelLogout { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("protocol")]
  public string? Protocol { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("attributes")]
  public Dictionary<string, string?>? Attributes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authenticationFlowBindingOverrides")]
  public Dictionary<string, string?>? AuthenticationFlowBindingOverrides { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("fullScopeAllowed")]
  public bool? FullScopeAllowed { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("nodeReRegistrationTimeout")]
  public int? NodeReRegistrationTimeout { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("registeredNodes")]
  public Dictionary<string, int>? RegisteredNodes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("protocolMappers")]
  public List<ProtocolMapperRepresentation>? ProtocolMappers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientTemplate")]
  public string? ClientTemplate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useTemplateConfig")]
  public bool? UseTemplateConfig { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useTemplateScope")]
  public bool? UseTemplateScope { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("useTemplateMappers")]
  public bool? UseTemplateMappers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("defaultClientScopes")]
  public List<string?>? DefaultClientScopes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("optionalClientScopes")]
  public List<string?>? OptionalClientScopes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authorizationSettings")]
  public ResourceServerRepresentation? AuthorizationSettings { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("access")]
  public Dictionary<string, bool>? Access { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("origin")]
  public string? Origin { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("claims")]
  public ClaimRepresentation? Claims { get; set; }
}
