//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// AuthenticationExecutionInfoRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/AuthenticationExecutionInfoRepresentation
/// </summary>
public class AuthenticationExecutionInfoRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requirement")]
  public string? Requirement { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("displayName")]
  public string? DisplayName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("alias")]
  public string? Alias { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requirementChoices")]
  public List<string?>? RequirementChoices { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("configurable")]
  public bool? Configurable { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authenticationFlow")]
  public bool? AuthenticationFlow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerId")]
  public string? ProviderId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authenticationConfig")]
  public string? AuthenticationConfig { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("flowId")]
  public string? FlowId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("level")]
  public int? Level { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("index")]
  public int? Index { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("priority")]
  public int? Priority { get; set; }
}
