//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// AuthDetailsRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/AuthDetailsRepresentation
/// </summary>
public class AuthDetailsRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("realmId")]
  public string? RealmId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientId")]
  public string? ClientId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public string? UserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ipAddress")]
  public string? IpAddress { get; set; }
}
