//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// AuthenticatorConfigRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/AuthenticatorConfigRepresentation
/// </summary>
public class AuthenticatorConfigRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("alias")]
  public string? Alias { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("config")]
  public Dictionary<string, string?>? Config { get; set; }
}
