//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// AuthorizationDetailsJSONRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/AuthorizationDetailsJSONRepresentation
/// </summary>
public partial class AuthorizationDetailsJsonRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("locations")]
  public List<string?>? Locations { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("actions")]
  public List<string?>? Actions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("datatypes")]
  public List<string?>? Datatypes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("identifier")]
  public string? Identifier { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("privileges")]
  public List<string?>? Privileges { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("customData")]
  public Dictionary<string, object?>? CustomData { get; set; }
}
