//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// AuthenticationExecutionExportRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/AuthenticationExecutionExportRepresentation
/// </summary>
public class AuthenticationExecutionExportRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("authenticatorConfig")]
  public string? AuthenticatorConfig { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authenticator")]
  public string? Authenticator { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authenticatorFlow")]
  public bool? AuthenticatorFlow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requirement")]
  public string? Requirement { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("priority")]
  public int? Priority { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("autheticatorFlow")]
  public bool? AutheticatorFlow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("flowAlias")]
  public string? FlowAlias { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userSetupAllowed")]
  public bool? UserSetupAllowed { get; set; }
}
