//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// CertificateRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/CertificateRepresentation
/// </summary>
public class CertificateRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("privateKey")]
  public string? PrivateKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("publicKey")]
  public string? PublicKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("certificate")]
  public string? Certificate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("kid")]
  public string? Kid { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("jwks")]
  public string? Jwks { get; set; }
}
