//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// ClaimRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/ClaimRepresentation
/// </summary>
public class ClaimRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public bool? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public bool? Username { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("profile")]
  public bool? Profile { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("picture")]
  public bool? Picture { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("website")]
  public bool? Website { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public bool? Email { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("gender")]
  public bool? Gender { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("locale")]
  public bool? Locale { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("address")]
  public bool? Address { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("phone")]
  public bool? Phone { get; set; }
}
