//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// ClientPolicyRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/ClientPolicyRepresentation
/// </summary>
public class ClientPolicyRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("conditions")]
  public List<ClientPolicyConditionRepresentation>? Conditions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("profiles")]
  public List<string?>? Profiles { get; set; }
}
