//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// Request model for ClientRepresentation
/// </summary>
public class ClientRepresentationRequest
{
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("clientId")]
  public string? ClientId { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("description")]
  public string? Description { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("type")]
  public string? Type { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("rootUrl")]
  public string? RootUrl { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("adminUrl")]
  public string? AdminUrl { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("baseUrl")]
  public string? BaseUrl { get; set; }

  [JsonPropertyName("surrogateAuthRequired")]
  public bool? SurrogateAuthRequired { get; set; }

  [JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [JsonPropertyName("alwaysDisplayInConsole")]
  public bool? AlwaysDisplayInConsole { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("clientAuthenticatorType")]
  public string? ClientAuthenticatorType { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("secret")]
  public string? Secret { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("registrationAccessToken")]
  public string? RegistrationAccessToken { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("defaultRoles")]
  public List<string?>? DefaultRoles { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("redirectUris")]
  public List<string?>? RedirectUris { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webOrigins")]
  public List<string?>? WebOrigins { get; set; }

  [JsonPropertyName("notBefore")]
  public int? NotBefore { get; set; }

  [JsonPropertyName("bearerOnly")]
  public bool? BearerOnly { get; set; }

  [JsonPropertyName("consentRequired")]
  public bool? ConsentRequired { get; set; }

  [JsonPropertyName("standardFlowEnabled")]
  public bool? StandardFlowEnabled { get; set; }

  [JsonPropertyName("implicitFlowEnabled")]
  public bool? ImplicitFlowEnabled { get; set; }

  [JsonPropertyName("directAccessGrantsEnabled")]
  public bool? DirectAccessGrantsEnabled { get; set; }

  [JsonPropertyName("serviceAccountsEnabled")]
  public bool? ServiceAccountsEnabled { get; set; }

  [JsonPropertyName("authorizationServicesEnabled")]
  public bool? AuthorizationServicesEnabled { get; set; }

  [JsonPropertyName("directGrantsOnly")]
  public bool? DirectGrantsOnly { get; set; }

  [JsonPropertyName("publicClient")]
  public bool? PublicClient { get; set; }

  [JsonPropertyName("frontchannelLogout")]
  public bool? FrontchannelLogout { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("protocol")]
  public string? Protocol { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("attributes")]
  public Dictionary<string, string?>? Attributes { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("authenticationFlowBindingOverrides")]
  public Dictionary<string, string?>? AuthenticationFlowBindingOverrides { get; set; }

  [JsonPropertyName("fullScopeAllowed")]
  public bool? FullScopeAllowed { get; set; }

  [JsonPropertyName("nodeReRegistrationTimeout")]
  public int? NodeReRegistrationTimeout { get; set; }

  [JsonPropertyName("registeredNodes")]
  public Dictionary<string, int>? RegisteredNodes { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("protocolMappers")]
  public List<ProtocolMapperRepresentation>? ProtocolMappers { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("clientTemplate")]
  public string? ClientTemplate { get; set; }

  [JsonPropertyName("useTemplateConfig")]
  public bool? UseTemplateConfig { get; set; }

  [JsonPropertyName("useTemplateScope")]
  public bool? UseTemplateScope { get; set; }

  [JsonPropertyName("useTemplateMappers")]
  public bool? UseTemplateMappers { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("defaultClientScopes")]
  public List<string?>? DefaultClientScopes { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("optionalClientScopes")]
  public List<string?>? OptionalClientScopes { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("authorizationSettings")]
  public ResourceServerRepresentation? AuthorizationSettings { get; set; }

  [JsonPropertyName("access")]
  public Dictionary<string, bool>? Access { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("origin")]
  public string? Origin { get; set; }

}
