//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// ClientTemplateRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/ClientTemplateRepresentation
/// </summary>
public class ClientTemplateRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("protocol")]
  public string? Protocol { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("fullScopeAllowed")]
  public bool? FullScopeAllowed { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("bearerOnly")]
  public bool? BearerOnly { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("consentRequired")]
  public bool? ConsentRequired { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("standardFlowEnabled")]
  public bool? StandardFlowEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("implicitFlowEnabled")]
  public bool? ImplicitFlowEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("directAccessGrantsEnabled")]
  public bool? DirectAccessGrantsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("serviceAccountsEnabled")]
  public bool? ServiceAccountsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("publicClient")]
  public bool? PublicClient { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("frontchannelLogout")]
  public bool? FrontchannelLogout { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("attributes")]
  public Dictionary<string, string?>? Attributes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("protocolMappers")]
  public List<ProtocolMapperRepresentation>? ProtocolMappers { get; set; }
}
