//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// ClientInitialAccessPresentation from OpenAPI schema.
/// Schema path: #/components/schemas/ClientInitialAccessPresentation
/// </summary>
public class ClientInitialAccessPresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("token")]
  public string? Token { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("timestamp")]
  public int? Timestamp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("expiration")]
  public int? Expiration { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("count")]
  public int? Count { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("remainingCount")]
  public int? RemainingCount { get; set; }
}
