//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// ComponentRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/ComponentRepresentation
/// </summary>
public class ComponentRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerId")]
  public string? ProviderId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerType")]
  public string? ProviderType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("parentId")]
  public string? ParentId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("subType")]
  public string? SubType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("config")]
  public MultivaluedHashMapStringString? Config { get; set; }
}
