//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// ComponentTypeRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/ComponentTypeRepresentation
/// </summary>
public class ComponentTypeRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("helpText")]
  public string? HelpText { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("properties")]
  public List<ConfigPropertyRepresentation>? Properties { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientProperties")]
  public List<ConfigPropertyRepresentation>? ClientProperties { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("metadata")]
  public Dictionary<string, object?>? Metadata { get; set; }
}
