//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// ConfigPropertyRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/ConfigPropertyRepresentation
/// </summary>
public class ConfigPropertyRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("label")]
  public string? Label { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("helpText")]
  public string? HelpText { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("defaultValue")]
  public object? DefaultValue { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("options")]
  public List<string?>? Options { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("secret")]
  public bool? Secret { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("required")]
  public bool? Required { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("readOnly")]
  public bool? ReadOnly { get; set; }
}
