//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// CredentialRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/CredentialRepresentation
/// </summary>
public class CredentialRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userLabel")]
  public string? UserLabel { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("createdDate")]
  public long? CreatedDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("secretData")]
  public string? SecretData { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("credentialData")]
  public string? CredentialData { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("priority")]
  public int? Priority { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("value")]
  public string? Value { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("temporary")]
  public bool? Temporary { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("device")]
  public string? Device { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hashedSaltedValue")]
  public string? HashedSaltedValue { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("salt")]
  public string? Salt { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hashIterations")]
  public int? HashIterations { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("counter")]
  public int? Counter { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("algorithm")]
  public string? Algorithm { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("digits")]
  public int? Digits { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("period")]
  public int? Period { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("config")]
  public MultivaluedHashMapStringString? Config { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("federationLink")]
  public string? FederationLink { get; set; }
}
