//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// ErrorRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/ErrorRepresentation
/// </summary>
public class ErrorRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("field")]
  public string? Field { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("errorMessage")]
  public string? ErrorMessage { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("params")]
  public List<object?>? Params { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("errors")]
  public List<ErrorRepresentation>? Errors { get; set; }
}
