//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// EvaluationResultRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/EvaluationResultRepresentation
/// </summary>
public class EvaluationResultRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("resource")]
  public ResourceRepresentation? Resource { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("scopes")]
  public List<ScopeRepresentation>? Scopes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("policies")]
  public List<PolicyResultRepresentation>? Policies { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public DecisionEffect? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("allowedScopes")]
  public List<ScopeRepresentation>? AllowedScopes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("deniedScopes")]
  public List<ScopeRepresentation>? DeniedScopes { get; set; }
}
