//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// GlobalRequestResult from OpenAPI schema.
/// Schema path: #/components/schemas/GlobalRequestResult
/// </summary>
public class GlobalRequestResult
{
  [System.Text.Json.Serialization.JsonPropertyName("successRequests")]
  public List<string?>? SuccessRequests { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("failedRequests")]
  public List<string?>? FailedRequests { get; set; }
}
