//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// GroupRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/GroupRepresentation
/// </summary>
public class GroupRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("path")]
  public string? Path { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("parentId")]
  public string? ParentId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("subGroupCount")]
  public long? SubGroupCount { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("subGroups")]
  public List<GroupRepresentation>? SubGroups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("attributes")]
  public Dictionary<string, List<string?>?>? Attributes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("realmRoles")]
  public List<string?>? RealmRoles { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientRoles")]
  public Dictionary<string, List<string?>?>? ClientRoles { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("access")]
  public Dictionary<string, bool>? Access { get; set; }
}
