//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// IdentityProviderRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/IdentityProviderRepresentation
/// </summary>
public class IdentityProviderRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("alias")]
  public string? Alias { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("displayName")]
  public string? DisplayName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("internalId")]
  public string? InternalId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerId")]
  public string? ProviderId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("updateProfileFirstLoginMode")]
  public string? UpdateProfileFirstLoginMode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("trustEmail")]
  public bool? TrustEmail { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("storeToken")]
  public bool? StoreToken { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("addReadTokenRoleOnCreate")]
  public bool? AddReadTokenRoleOnCreate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authenticateByDefault")]
  public bool? AuthenticateByDefault { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("linkOnly")]
  public bool? LinkOnly { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("hideOnLogin")]
  public bool? HideOnLogin { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("firstBrokerLoginFlowAlias")]
  public string? FirstBrokerLoginFlowAlias { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("postBrokerLoginFlowAlias")]
  public string? PostBrokerLoginFlowAlias { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizationId")]
  public string? OrganizationId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("config")]
  public Dictionary<string, string?>? Config { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("types")]
  public List<string?>? Types { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("updateProfileFirstLogin")]
  public bool? UpdateProfileFirstLogin { get; set; }
}
