//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// InstallationAdapterConfig from OpenAPI schema.
/// Schema path: #/components/schemas/InstallationAdapterConfig
/// </summary>
public class InstallationAdapterConfig
{
  [System.Text.Json.Serialization.JsonPropertyName("realm")]
  public string? Realm { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("realm-public-key")]
  public string? RealmPublicKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("auth-server-url")]
  public string? AuthServerUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ssl-required")]
  public string? SslRequired { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("bearer-only")]
  public bool? BearerOnly { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resource")]
  public string? Resource { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("public-client")]
  public bool? PublicClient { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("verify-token-audience")]
  public bool? VerifyTokenAudience { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("credentials")]
  public Dictionary<string, object?>? Credentials { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("use-resource-role-mappings")]
  public bool? UseResourceRoleMappings { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("confidential-port")]
  public int? ConfidentialPort { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("policy-enforcer")]
  public PolicyEnforcerConfig? PolicyEnforcer { get; set; }
}
