//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// IssuedVerifiableCredentialRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/IssuedVerifiableCredentialRepresentation
/// </summary>
public partial class IssuedVerifiableCredentialRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public string? UserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("credentialType")]
  public string? CredentialType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("issuedAt")]
  public long? IssuedAt { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("expiresAt")]
  public long? ExpiresAt { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientId")]
  public string? ClientId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientName")]
  public string? ClientName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientBaseUrl")]
  public string? ClientBaseUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("revision")]
  public string? Revision { get; set; }
}
