//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// KeyMetadataRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/KeyMetadataRepresentation
/// </summary>
public class KeyMetadataRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("providerId")]
  public string? ProviderId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerPriority")]
  public long? ProviderPriority { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("kid")]
  public string? Kid { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public string? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("algorithm")]
  public string? Algorithm { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("publicKey")]
  public string? PublicKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("certificate")]
  public string? Certificate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("use")]
  public KeyUse? Use { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("validTo")]
  public long? ValidTo { get; set; }
}
