//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// KeyStoreConfig from OpenAPI schema.
/// Schema path: #/components/schemas/KeyStoreConfig
/// </summary>
public class KeyStoreConfig
{
  [System.Text.Json.Serialization.JsonPropertyName("realmCertificate")]
  public bool? RealmCertificate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("storePassword")]
  public string? StorePassword { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("keyPassword")]
  public string? KeyPassword { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("keyAlias")]
  public string? KeyAlias { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("realmAlias")]
  public string? RealmAlias { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("format")]
  public string? Format { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("keySize")]
  public int? KeySize { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("validity")]
  public int? Validity { get; set; }
}
