//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// Extension methods for converting between Request and Response models
/// </summary>
public static class ModelConversionExtensions
{
  /// <summary>
  /// Converts ResourceRepresentation to ResourceRepresentationRequest
  /// </summary>
  public static ResourceRepresentationRequest ToRequest(this ResourceRepresentation source)
  {
    return new ResourceRepresentationRequest
    {
      Id = source.Id,
      Name = source.Name,
      Uris = source.Uris,
      Type = source.Type,
      Scopes = source.Scopes,
      IconUri = source.IconUri,
      OwnerManagedAccess = source.OwnerManagedAccess,
      DisplayName = source.DisplayName,
      Attributes = source.Attributes,
      ScopesUma = source.ScopesUma
    };
  }

}
