//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// Extension methods for converting between Request and Response models
/// </summary>
public static class ModelConversionExtensions
{
  /// <summary>
  /// Converts ResourceServerRepresentation to ResourceServerRepresentationRequest
  /// </summary>
  public static ResourceServerRepresentationRequest ToRequest(this ResourceServerRepresentation source)
  {
    return new ResourceServerRepresentationRequest
    {
      Id = source.Id,
      ClientId = source.ClientId,
      Name = source.Name,
      AllowRemoteResourceManagement = source.AllowRemoteResourceManagement,
      PolicyEnforcementMode = source.PolicyEnforcementMode,
      Resources = source.Resources,
      Policies = source.Policies,
      Scopes = source.Scopes,
      DecisionStrategy = source.DecisionStrategy,
      AuthorizationSchema = source.AuthorizationSchema
    };
  }

  /// <summary>
  /// Converts ClientRepresentation to ClientRepresentationRequest
  /// </summary>
  public static ClientRepresentationRequest ToRequest(this ClientRepresentation source)
  {
    return new ClientRepresentationRequest
    {
      Id = source.Id,
      ClientId = source.ClientId,
      Name = source.Name,
      Description = source.Description,
      Type = source.Type,
      RootUrl = source.RootUrl,
      AdminUrl = source.AdminUrl,
      BaseUrl = source.BaseUrl,
      SurrogateAuthRequired = source.SurrogateAuthRequired,
      Enabled = source.Enabled,
      AlwaysDisplayInConsole = source.AlwaysDisplayInConsole,
      ClientAuthenticatorType = source.ClientAuthenticatorType,
      Secret = source.Secret,
      RegistrationAccessToken = source.RegistrationAccessToken,
      DefaultRoles = source.DefaultRoles,
      RedirectUris = source.RedirectUris,
      WebOrigins = source.WebOrigins,
      NotBefore = source.NotBefore,
      BearerOnly = source.BearerOnly,
      ConsentRequired = source.ConsentRequired,
      StandardFlowEnabled = source.StandardFlowEnabled,
      ImplicitFlowEnabled = source.ImplicitFlowEnabled,
      DirectAccessGrantsEnabled = source.DirectAccessGrantsEnabled,
      ServiceAccountsEnabled = source.ServiceAccountsEnabled,
      AuthorizationServicesEnabled = source.AuthorizationServicesEnabled,
      DirectGrantsOnly = source.DirectGrantsOnly,
      PublicClient = source.PublicClient,
      FrontchannelLogout = source.FrontchannelLogout,
      Protocol = source.Protocol,
      Attributes = source.Attributes,
      AuthenticationFlowBindingOverrides = source.AuthenticationFlowBindingOverrides,
      FullScopeAllowed = source.FullScopeAllowed,
      NodeReRegistrationTimeout = source.NodeReRegistrationTimeout,
      RegisteredNodes = source.RegisteredNodes,
      ProtocolMappers = source.ProtocolMappers,
      ClientTemplate = source.ClientTemplate,
      UseTemplateConfig = source.UseTemplateConfig,
      UseTemplateScope = source.UseTemplateScope,
      UseTemplateMappers = source.UseTemplateMappers,
      DefaultClientScopes = source.DefaultClientScopes,
      OptionalClientScopes = source.OptionalClientScopes,
      AuthorizationSettings = source.AuthorizationSettings,
      Access = source.Access,
      Origin = source.Origin
    };
  }

  /// <summary>
  /// Converts ResourceRepresentation to ResourceRepresentationRequest
  /// </summary>
  public static ResourceRepresentationRequest ToRequest(this ResourceRepresentation source)
  {
    return new ResourceRepresentationRequest
    {
      Id = source.Id,
      Name = source.Name,
      Uris = source.Uris,
      Type = source.Type,
      Scopes = source.Scopes,
      IconUri = source.IconUri,
      OwnerManagedAccess = source.OwnerManagedAccess,
      DisplayName = source.DisplayName,
      Attributes = source.Attributes,
      ScopesUma = source.ScopesUma
    };
  }

  /// <summary>
  /// Converts RealmRepresentation to RealmRepresentationRequest
  /// </summary>
  public static RealmRepresentationRequest ToRequest(this RealmRepresentation source)
  {
    return new RealmRepresentationRequest
    {
      Id = source.Id,
      Realm = source.Realm,
      DisplayName = source.DisplayName,
      DisplayNameHtml = source.DisplayNameHtml,
      NotBefore = source.NotBefore,
      DefaultSignatureAlgorithm = source.DefaultSignatureAlgorithm,
      RevokeRefreshToken = source.RevokeRefreshToken,
      RefreshTokenMaxReuse = source.RefreshTokenMaxReuse,
      AccessTokenLifespan = source.AccessTokenLifespan,
      AccessTokenLifespanForImplicitFlow = source.AccessTokenLifespanForImplicitFlow,
      SsoSessionIdleTimeout = source.SsoSessionIdleTimeout,
      SsoSessionMaxLifespan = source.SsoSessionMaxLifespan,
      SsoSessionIdleTimeoutRememberMe = source.SsoSessionIdleTimeoutRememberMe,
      SsoSessionMaxLifespanRememberMe = source.SsoSessionMaxLifespanRememberMe,
      OfflineSessionIdleTimeout = source.OfflineSessionIdleTimeout,
      OfflineSessionMaxLifespanEnabled = source.OfflineSessionMaxLifespanEnabled,
      OfflineSessionMaxLifespan = source.OfflineSessionMaxLifespan,
      ClientSessionIdleTimeout = source.ClientSessionIdleTimeout,
      ClientSessionMaxLifespan = source.ClientSessionMaxLifespan,
      ClientOfflineSessionIdleTimeout = source.ClientOfflineSessionIdleTimeout,
      ClientOfflineSessionMaxLifespan = source.ClientOfflineSessionMaxLifespan,
      AccessCodeLifespan = source.AccessCodeLifespan,
      AccessCodeLifespanUserAction = source.AccessCodeLifespanUserAction,
      AccessCodeLifespanLogin = source.AccessCodeLifespanLogin,
      ActionTokenGeneratedByAdminLifespan = source.ActionTokenGeneratedByAdminLifespan,
      ActionTokenGeneratedByUserLifespan = source.ActionTokenGeneratedByUserLifespan,
      Oauth2DeviceCodeLifespan = source.Oauth2DeviceCodeLifespan,
      Oauth2DevicePollingInterval = source.Oauth2DevicePollingInterval,
      Enabled = source.Enabled,
      SslRequired = source.SslRequired,
      PasswordCredentialGrantAllowed = source.PasswordCredentialGrantAllowed,
      RegistrationAllowed = source.RegistrationAllowed,
      RegistrationEmailAsUsername = source.RegistrationEmailAsUsername,
      RememberMe = source.RememberMe,
      VerifyEmail = source.VerifyEmail,
      LoginWithEmailAllowed = source.LoginWithEmailAllowed,
      DuplicateEmailsAllowed = source.DuplicateEmailsAllowed,
      ResetPasswordAllowed = source.ResetPasswordAllowed,
      EditUsernameAllowed = source.EditUsernameAllowed,
      UserCacheEnabled = source.UserCacheEnabled,
      RealmCacheEnabled = source.RealmCacheEnabled,
      BruteForceProtected = source.BruteForceProtected,
      PermanentLockout = source.PermanentLockout,
      MaxTemporaryLockouts = source.MaxTemporaryLockouts,
      BruteForceStrategy = source.BruteForceStrategy,
      MaxFailureWaitSeconds = source.MaxFailureWaitSeconds,
      MinimumQuickLoginWaitSeconds = source.MinimumQuickLoginWaitSeconds,
      WaitIncrementSeconds = source.WaitIncrementSeconds,
      QuickLoginCheckMilliSeconds = source.QuickLoginCheckMilliSeconds,
      MaxDeltaTimeSeconds = source.MaxDeltaTimeSeconds,
      FailureFactor = source.FailureFactor,
      PrivateKey = source.PrivateKey,
      PublicKey = source.PublicKey,
      Certificate = source.Certificate,
      CodeSecret = source.CodeSecret,
      Roles = source.Roles,
      Groups = source.Groups,
      DefaultRoles = source.DefaultRoles,
      DefaultRole = source.DefaultRole,
      AdminPermissionsClient = source.AdminPermissionsClient,
      DefaultGroups = source.DefaultGroups,
      RequiredCredentials = source.RequiredCredentials,
      PasswordPolicy = source.PasswordPolicy,
      OtpPolicyType = source.OtpPolicyType,
      OtpPolicyAlgorithm = source.OtpPolicyAlgorithm,
      OtpPolicyInitialCounter = source.OtpPolicyInitialCounter,
      OtpPolicyDigits = source.OtpPolicyDigits,
      OtpPolicyLookAheadWindow = source.OtpPolicyLookAheadWindow,
      OtpPolicyPeriod = source.OtpPolicyPeriod,
      OtpPolicyCodeReusable = source.OtpPolicyCodeReusable,
      OtpSupportedApplications = source.OtpSupportedApplications,
      LocalizationTexts = source.LocalizationTexts,
      WebAuthnPolicyRpEntityName = source.WebAuthnPolicyRpEntityName,
      WebAuthnPolicySignatureAlgorithms = source.WebAuthnPolicySignatureAlgorithms,
      WebAuthnPolicyRpId = source.WebAuthnPolicyRpId,
      WebAuthnPolicyAttestationConveyancePreference = source.WebAuthnPolicyAttestationConveyancePreference,
      WebAuthnPolicyAuthenticatorAttachment = source.WebAuthnPolicyAuthenticatorAttachment,
      WebAuthnPolicyRequireResidentKey = source.WebAuthnPolicyRequireResidentKey,
      WebAuthnPolicyUserVerificationRequirement = source.WebAuthnPolicyUserVerificationRequirement,
      WebAuthnPolicyCreateTimeout = source.WebAuthnPolicyCreateTimeout,
      WebAuthnPolicyAvoidSameAuthenticatorRegister = source.WebAuthnPolicyAvoidSameAuthenticatorRegister,
      WebAuthnPolicyAcceptableAaguids = source.WebAuthnPolicyAcceptableAaguids,
      WebAuthnPolicyExtraOrigins = source.WebAuthnPolicyExtraOrigins,
      WebAuthnPolicyPasswordlessRpEntityName = source.WebAuthnPolicyPasswordlessRpEntityName,
      WebAuthnPolicyPasswordlessSignatureAlgorithms = source.WebAuthnPolicyPasswordlessSignatureAlgorithms,
      WebAuthnPolicyPasswordlessRpId = source.WebAuthnPolicyPasswordlessRpId,
      WebAuthnPolicyPasswordlessAttestationConveyancePreference = source.WebAuthnPolicyPasswordlessAttestationConveyancePreference,
      WebAuthnPolicyPasswordlessAuthenticatorAttachment = source.WebAuthnPolicyPasswordlessAuthenticatorAttachment,
      WebAuthnPolicyPasswordlessRequireResidentKey = source.WebAuthnPolicyPasswordlessRequireResidentKey,
      WebAuthnPolicyPasswordlessUserVerificationRequirement = source.WebAuthnPolicyPasswordlessUserVerificationRequirement,
      WebAuthnPolicyPasswordlessCreateTimeout = source.WebAuthnPolicyPasswordlessCreateTimeout,
      WebAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister = source.WebAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister,
      WebAuthnPolicyPasswordlessAcceptableAaguids = source.WebAuthnPolicyPasswordlessAcceptableAaguids,
      WebAuthnPolicyPasswordlessExtraOrigins = source.WebAuthnPolicyPasswordlessExtraOrigins,
      WebAuthnPolicyPasswordlessPasskeysEnabled = source.WebAuthnPolicyPasswordlessPasskeysEnabled,
      ClientProfiles = source.ClientProfiles,
      ClientPolicies = source.ClientPolicies,
      Users = source.Users,
      FederatedUsers = source.FederatedUsers,
      ScopeMappings = source.ScopeMappings,
      ClientScopeMappings = source.ClientScopeMappings,
      Clients = source.Clients,
      ClientScopes = source.ClientScopes,
      DefaultDefaultClientScopes = source.DefaultDefaultClientScopes,
      DefaultOptionalClientScopes = source.DefaultOptionalClientScopes,
      BrowserSecurityHeaders = source.BrowserSecurityHeaders,
      SmtpServer = source.SmtpServer,
      UserFederationProviders = source.UserFederationProviders,
      UserFederationMappers = source.UserFederationMappers,
      LoginTheme = source.LoginTheme,
      AccountTheme = source.AccountTheme,
      AdminTheme = source.AdminTheme,
      EmailTheme = source.EmailTheme,
      EventsEnabled = source.EventsEnabled,
      EventsExpiration = source.EventsExpiration,
      EventsListeners = source.EventsListeners,
      EnabledEventTypes = source.EnabledEventTypes,
      AdminEventsEnabled = source.AdminEventsEnabled,
      AdminEventsDetailsEnabled = source.AdminEventsDetailsEnabled,
      IdentityProviders = source.IdentityProviders,
      IdentityProviderMappers = source.IdentityProviderMappers,
      ProtocolMappers = source.ProtocolMappers,
      Components = source.Components,
      InternationalizationEnabled = source.InternationalizationEnabled,
      SupportedLocales = source.SupportedLocales,
      DefaultLocale = source.DefaultLocale,
      AuthenticationFlows = source.AuthenticationFlows,
      AuthenticatorConfig = source.AuthenticatorConfig,
      RequiredActions = source.RequiredActions,
      BrowserFlow = source.BrowserFlow,
      RegistrationFlow = source.RegistrationFlow,
      DirectGrantFlow = source.DirectGrantFlow,
      ResetCredentialsFlow = source.ResetCredentialsFlow,
      ClientAuthenticationFlow = source.ClientAuthenticationFlow,
      DockerAuthenticationFlow = source.DockerAuthenticationFlow,
      FirstBrokerLoginFlow = source.FirstBrokerLoginFlow,
      Attributes = source.Attributes,
      KeycloakVersion = source.KeycloakVersion,
      UserManagedAccessAllowed = source.UserManagedAccessAllowed,
      OrganizationsEnabled = source.OrganizationsEnabled,
      Organizations = source.Organizations,
      VerifiableCredentialsEnabled = source.VerifiableCredentialsEnabled,
      AdminPermissionsEnabled = source.AdminPermissionsEnabled,
      Social = source.Social,
      UpdateProfileOnInitialSocialLogin = source.UpdateProfileOnInitialSocialLogin,
      SocialProviders = source.SocialProviders,
      ApplicationScopeMappings = source.ApplicationScopeMappings,
      Applications = source.Applications,
      OauthClients = source.OauthClients,
      ClientTemplates = source.ClientTemplates
    };
  }

  /// <summary>
  /// Converts ScopeRepresentation to ScopeRepresentationRequest
  /// </summary>
  public static ScopeRepresentationRequest ToRequest(this ScopeRepresentation source)
  {
    return new ScopeRepresentationRequest
    {
      Id = source.Id,
      Name = source.Name,
      IconUri = source.IconUri,
      Policies = source.Policies,
      Resources = source.Resources,
      DisplayName = source.DisplayName
    };
  }

  /// <summary>
  /// Converts WorkflowRepresentation to WorkflowRepresentationRequest
  /// </summary>
  public static WorkflowRepresentationRequest ToRequest(this WorkflowRepresentation source)
  {
    return new WorkflowRepresentationRequest
    {
      Id = source.Id,
      Name = source.Name,
      Enabled = source.Enabled,
      On = source.On,
      Schedule = source.Schedule,
      Concurrency = source.Concurrency,
      If = source.If,
      Steps = source.Steps,
      State = source.State,
      With = source.With,
      CancelInProgress = source.CancelInProgress,
      RestartInProgress = source.RestartInProgress
    };
  }

}
