//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// OrganizationRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/OrganizationRepresentation
/// </summary>
public class OrganizationRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("alias")]
  public string? Alias { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("redirectUrl")]
  public string? RedirectUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("attributes")]
  public Dictionary<string, List<string?>?>? Attributes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("domains")]
  public List<OrganizationDomainRepresentation>? Domains { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("members")]
  public List<MemberRepresentation>? Members { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("identityProviders")]
  public List<IdentityProviderRepresentation>? IdentityProviders { get; set; }
}
