//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// OrganizationInvitationRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/OrganizationInvitationRepresentation
/// </summary>
public class OrganizationInvitationRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizationId")]
  public string? OrganizationId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("firstName")]
  public string? FirstName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("lastName")]
  public string? LastName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("sentDate")]
  public int? SentDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("expiresAt")]
  public int? ExpiresAt { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("status")]
  public Status? Status { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("inviteLink")]
  public string? InviteLink { get; set; }
}
