//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// PathCacheConfig from OpenAPI schema.
/// Schema path: #/components/schemas/PathCacheConfig
/// </summary>
public class PathCacheConfig
{
  [System.Text.Json.Serialization.JsonPropertyName("max-entries")]
  public int? MaxEntries { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("lifespan")]
  public long? Lifespan { get; set; }
}
