//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// PathConfig from OpenAPI schema.
/// Schema path: #/components/schemas/PathConfig
/// </summary>
public class PathConfig
{
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("path")]
  public string? Path { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("methods")]
  public List<MethodConfig>? Methods { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("scopes")]
  public List<string?>? Scopes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enforcement-mode")]
  public EnforcementMode? EnforcementMode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("claim-information-point")]
  public Dictionary<string, Dictionary<string, object?>?>? ClaimInformationPoint { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("invalidated")]
  public bool? Invalidated { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("staticPath")]
  public bool? StaticPath { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("static")]
  public bool? Static { get; set; }
}
