//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// Permission from OpenAPI schema.
/// Schema path: #/components/schemas/Permission
/// </summary>
public class Permission
{
  [System.Text.Json.Serialization.JsonPropertyName("rsid")]
  public string? Rsid { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rsname")]
  public string? Rsname { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("scopes")]
  public List<string?>? Scopes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("claims")]
  public Dictionary<string, List<string?>?>? Claims { get; set; }
}
