//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// PolicyRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/PolicyRepresentation
/// </summary>
public class PolicyRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("type")]
  public string? Type { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("policies")]
  public List<string?>? Policies { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resources")]
  public List<string?>? Resources { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("scopes")]
  public List<string?>? Scopes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("logic")]
  public Logic? Logic { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("decisionStrategy")]
  public DecisionStrategy? DecisionStrategy { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("owner")]
  public string? Owner { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resourceType")]
  public string? ResourceType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resourcesData")]
  public List<ResourceRepresentation>? ResourcesData { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("scopesData")]
  public List<ScopeRepresentation>? ScopesData { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("config")]
  public Dictionary<string, string?>? Config { get; set; }
}
