//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// PolicyEnforcerConfig from OpenAPI schema.
/// Schema path: #/components/schemas/PolicyEnforcerConfig
/// </summary>
public class PolicyEnforcerConfig
{
  [System.Text.Json.Serialization.JsonPropertyName("enforcement-mode")]
  public EnforcementMode? EnforcementMode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("paths")]
  public List<PathConfig>? Paths { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("path-cache")]
  public PathCacheConfig? PathCache { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("lazy-load-paths")]
  public bool? LazyLoadPaths { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("on-deny-redirect-to")]
  public string? OnDenyRedirectTo { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("user-managed-access")]
  public UserManagedAccessConfig? UserManagedAccess { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("claim-information-point")]
  public Dictionary<string, Dictionary<string, object?>?>? ClaimInformationPoint { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("http-method-as-scope")]
  public bool? HttpMethodAsScope { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("realm")]
  public string? Realm { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("auth-server-url")]
  public string? AuthServerUrl { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("credentials")]
  public Dictionary<string, object?>? Credentials { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resource")]
  public string? Resource { get; set; }
}
