//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// ProtocolMapperEvaluationRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/ProtocolMapperEvaluationRepresentation
/// </summary>
public class ProtocolMapperEvaluationRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("mapperId")]
  public string? MapperId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("mapperName")]
  public string? MapperName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("containerId")]
  public string? ContainerId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("containerName")]
  public string? ContainerName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("containerType")]
  public string? ContainerType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("protocolMapper")]
  public string? ProtocolMapper { get; set; }
}
