//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// PublishedRealmRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/PublishedRealmRepresentation
/// </summary>
public class PublishedRealmRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("realm")]
  public string? Realm { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("public_key")]
  public string? PublicKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("token-service")]
  public string? TokenService { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("account-service")]
  public string? AccountService { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("tokens-not-before")]
  public int? TokensNotBefore { get; set; }
}
