//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// Request model for RealmRepresentation
/// </summary>
public class RealmRepresentationRequest
{
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("realm")]
  public string? Realm { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("displayName")]
  public string? DisplayName { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("displayNameHtml")]
  public string? DisplayNameHtml { get; set; }

  [JsonPropertyName("notBefore")]
  public int? NotBefore { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("defaultSignatureAlgorithm")]
  public string? DefaultSignatureAlgorithm { get; set; }

  [JsonPropertyName("revokeRefreshToken")]
  public bool? RevokeRefreshToken { get; set; }

  [JsonPropertyName("refreshTokenMaxReuse")]
  public int? RefreshTokenMaxReuse { get; set; }

  [JsonPropertyName("accessTokenLifespan")]
  public int? AccessTokenLifespan { get; set; }

  [JsonPropertyName("accessTokenLifespanForImplicitFlow")]
  public int? AccessTokenLifespanForImplicitFlow { get; set; }

  [JsonPropertyName("ssoSessionIdleTimeout")]
  public int? SsoSessionIdleTimeout { get; set; }

  [JsonPropertyName("ssoSessionMaxLifespan")]
  public int? SsoSessionMaxLifespan { get; set; }

  [JsonPropertyName("ssoSessionIdleTimeoutRememberMe")]
  public int? SsoSessionIdleTimeoutRememberMe { get; set; }

  [JsonPropertyName("ssoSessionMaxLifespanRememberMe")]
  public int? SsoSessionMaxLifespanRememberMe { get; set; }

  [JsonPropertyName("offlineSessionIdleTimeout")]
  public int? OfflineSessionIdleTimeout { get; set; }

  [JsonPropertyName("offlineSessionMaxLifespanEnabled")]
  public bool? OfflineSessionMaxLifespanEnabled { get; set; }

  [JsonPropertyName("offlineSessionMaxLifespan")]
  public int? OfflineSessionMaxLifespan { get; set; }

  [JsonPropertyName("clientSessionIdleTimeout")]
  public int? ClientSessionIdleTimeout { get; set; }

  [JsonPropertyName("clientSessionMaxLifespan")]
  public int? ClientSessionMaxLifespan { get; set; }

  [JsonPropertyName("clientOfflineSessionIdleTimeout")]
  public int? ClientOfflineSessionIdleTimeout { get; set; }

  [JsonPropertyName("clientOfflineSessionMaxLifespan")]
  public int? ClientOfflineSessionMaxLifespan { get; set; }

  [JsonPropertyName("accessCodeLifespan")]
  public int? AccessCodeLifespan { get; set; }

  [JsonPropertyName("accessCodeLifespanUserAction")]
  public int? AccessCodeLifespanUserAction { get; set; }

  [JsonPropertyName("accessCodeLifespanLogin")]
  public int? AccessCodeLifespanLogin { get; set; }

  [JsonPropertyName("actionTokenGeneratedByAdminLifespan")]
  public int? ActionTokenGeneratedByAdminLifespan { get; set; }

  [JsonPropertyName("actionTokenGeneratedByUserLifespan")]
  public int? ActionTokenGeneratedByUserLifespan { get; set; }

  [JsonPropertyName("oauth2DeviceCodeLifespan")]
  public int? Oauth2DeviceCodeLifespan { get; set; }

  [JsonPropertyName("oauth2DevicePollingInterval")]
  public int? Oauth2DevicePollingInterval { get; set; }

  [JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("sslRequired")]
  public string? SslRequired { get; set; }

  [JsonPropertyName("passwordCredentialGrantAllowed")]
  public bool? PasswordCredentialGrantAllowed { get; set; }

  [JsonPropertyName("registrationAllowed")]
  public bool? RegistrationAllowed { get; set; }

  [JsonPropertyName("registrationEmailAsUsername")]
  public bool? RegistrationEmailAsUsername { get; set; }

  [JsonPropertyName("rememberMe")]
  public bool? RememberMe { get; set; }

  [JsonPropertyName("verifyEmail")]
  public bool? VerifyEmail { get; set; }

  [JsonPropertyName("loginWithEmailAllowed")]
  public bool? LoginWithEmailAllowed { get; set; }

  [JsonPropertyName("duplicateEmailsAllowed")]
  public bool? DuplicateEmailsAllowed { get; set; }

  [JsonPropertyName("resetPasswordAllowed")]
  public bool? ResetPasswordAllowed { get; set; }

  [JsonPropertyName("editUsernameAllowed")]
  public bool? EditUsernameAllowed { get; set; }

  [JsonPropertyName("userCacheEnabled")]
  public bool? UserCacheEnabled { get; set; }

  [JsonPropertyName("realmCacheEnabled")]
  public bool? RealmCacheEnabled { get; set; }

  [JsonPropertyName("bruteForceProtected")]
  public bool? BruteForceProtected { get; set; }

  [JsonPropertyName("permanentLockout")]
  public bool? PermanentLockout { get; set; }

  [JsonPropertyName("maxTemporaryLockouts")]
  public int? MaxTemporaryLockouts { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("bruteForceStrategy")]
  public BruteForceStrategy? BruteForceStrategy { get; set; }

  [JsonPropertyName("maxFailureWaitSeconds")]
  public int? MaxFailureWaitSeconds { get; set; }

  [JsonPropertyName("minimumQuickLoginWaitSeconds")]
  public int? MinimumQuickLoginWaitSeconds { get; set; }

  [JsonPropertyName("waitIncrementSeconds")]
  public int? WaitIncrementSeconds { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("quickLoginCheckMilliSeconds")]
  public long? QuickLoginCheckMilliSeconds { get; set; }

  [JsonPropertyName("maxDeltaTimeSeconds")]
  public int? MaxDeltaTimeSeconds { get; set; }

  [JsonPropertyName("failureFactor")]
  public int? FailureFactor { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("privateKey")]
  public string? PrivateKey { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("publicKey")]
  public string? PublicKey { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("certificate")]
  public string? Certificate { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("codeSecret")]
  public string? CodeSecret { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("roles")]
  public RolesRepresentation? Roles { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("groups")]
  public List<GroupRepresentation>? Groups { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("defaultRoles")]
  public List<string?>? DefaultRoles { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("defaultRole")]
  public RoleRepresentation? DefaultRole { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("adminPermissionsClient")]
  public ClientRepresentation? AdminPermissionsClient { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("defaultGroups")]
  public List<string?>? DefaultGroups { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("requiredCredentials")]
  public List<string?>? RequiredCredentials { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("passwordPolicy")]
  public string? PasswordPolicy { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("otpPolicyType")]
  public string? OtpPolicyType { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("otpPolicyAlgorithm")]
  public string? OtpPolicyAlgorithm { get; set; }

  [JsonPropertyName("otpPolicyInitialCounter")]
  public int? OtpPolicyInitialCounter { get; set; }

  [JsonPropertyName("otpPolicyDigits")]
  public int? OtpPolicyDigits { get; set; }

  [JsonPropertyName("otpPolicyLookAheadWindow")]
  public int? OtpPolicyLookAheadWindow { get; set; }

  [JsonPropertyName("otpPolicyPeriod")]
  public int? OtpPolicyPeriod { get; set; }

  [JsonPropertyName("otpPolicyCodeReusable")]
  public bool? OtpPolicyCodeReusable { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("otpSupportedApplications")]
  public List<string?>? OtpSupportedApplications { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("localizationTexts")]
  public Dictionary<string, Dictionary<string, string?>?>? LocalizationTexts { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyRpEntityName")]
  public string? WebAuthnPolicyRpEntityName { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicySignatureAlgorithms")]
  public List<string?>? WebAuthnPolicySignatureAlgorithms { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyRpId")]
  public string? WebAuthnPolicyRpId { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyAttestationConveyancePreference")]
  public string? WebAuthnPolicyAttestationConveyancePreference { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyAuthenticatorAttachment")]
  public string? WebAuthnPolicyAuthenticatorAttachment { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyRequireResidentKey")]
  public string? WebAuthnPolicyRequireResidentKey { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyUserVerificationRequirement")]
  public string? WebAuthnPolicyUserVerificationRequirement { get; set; }

  [JsonPropertyName("webAuthnPolicyCreateTimeout")]
  public int? WebAuthnPolicyCreateTimeout { get; set; }

  [JsonPropertyName("webAuthnPolicyAvoidSameAuthenticatorRegister")]
  public bool? WebAuthnPolicyAvoidSameAuthenticatorRegister { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyAcceptableAaguids")]
  public List<string?>? WebAuthnPolicyAcceptableAaguids { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyExtraOrigins")]
  public List<string?>? WebAuthnPolicyExtraOrigins { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyPasswordlessRpEntityName")]
  public string? WebAuthnPolicyPasswordlessRpEntityName { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyPasswordlessSignatureAlgorithms")]
  public List<string?>? WebAuthnPolicyPasswordlessSignatureAlgorithms { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyPasswordlessRpId")]
  public string? WebAuthnPolicyPasswordlessRpId { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyPasswordlessAttestationConveyancePreference")]
  public string? WebAuthnPolicyPasswordlessAttestationConveyancePreference { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyPasswordlessAuthenticatorAttachment")]
  public string? WebAuthnPolicyPasswordlessAuthenticatorAttachment { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyPasswordlessRequireResidentKey")]
  public string? WebAuthnPolicyPasswordlessRequireResidentKey { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyPasswordlessUserVerificationRequirement")]
  public string? WebAuthnPolicyPasswordlessUserVerificationRequirement { get; set; }

  [JsonPropertyName("webAuthnPolicyPasswordlessCreateTimeout")]
  public int? WebAuthnPolicyPasswordlessCreateTimeout { get; set; }

  [JsonPropertyName("webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister")]
  public bool? WebAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyPasswordlessAcceptableAaguids")]
  public List<string?>? WebAuthnPolicyPasswordlessAcceptableAaguids { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("webAuthnPolicyPasswordlessExtraOrigins")]
  public List<string?>? WebAuthnPolicyPasswordlessExtraOrigins { get; set; }

  [JsonPropertyName("webAuthnPolicyPasswordlessPasskeysEnabled")]
  public bool? WebAuthnPolicyPasswordlessPasskeysEnabled { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("clientProfiles")]
  public ClientProfilesRepresentation? ClientProfiles { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("clientPolicies")]
  public ClientPoliciesRepresentation? ClientPolicies { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("users")]
  public List<UserRepresentation>? Users { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("federatedUsers")]
  public List<UserRepresentation>? FederatedUsers { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("scopeMappings")]
  public List<ScopeMappingRepresentation>? ScopeMappings { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("clientScopeMappings")]
  public Dictionary<string, List<ScopeMappingRepresentation>?>? ClientScopeMappings { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("clients")]
  public List<ClientRepresentation>? Clients { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("clientScopes")]
  public List<ClientScopeRepresentation>? ClientScopes { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("defaultDefaultClientScopes")]
  public List<string?>? DefaultDefaultClientScopes { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("defaultOptionalClientScopes")]
  public List<string?>? DefaultOptionalClientScopes { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("browserSecurityHeaders")]
  public Dictionary<string, string?>? BrowserSecurityHeaders { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("smtpServer")]
  public Dictionary<string, string?>? SmtpServer { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("userFederationProviders")]
  public List<UserFederationProviderRepresentation>? UserFederationProviders { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("userFederationMappers")]
  public List<UserFederationMapperRepresentation>? UserFederationMappers { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("loginTheme")]
  public string? LoginTheme { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("accountTheme")]
  public string? AccountTheme { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("adminTheme")]
  public string? AdminTheme { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("emailTheme")]
  public string? EmailTheme { get; set; }

  [JsonPropertyName("eventsEnabled")]
  public bool? EventsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("eventsExpiration")]
  public long? EventsExpiration { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("eventsListeners")]
  public List<string?>? EventsListeners { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("enabledEventTypes")]
  public List<string?>? EnabledEventTypes { get; set; }

  [JsonPropertyName("adminEventsEnabled")]
  public bool? AdminEventsEnabled { get; set; }

  [JsonPropertyName("adminEventsDetailsEnabled")]
  public bool? AdminEventsDetailsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("identityProviders")]
  public List<IdentityProviderRepresentation>? IdentityProviders { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("identityProviderMappers")]
  public List<IdentityProviderMapperRepresentation>? IdentityProviderMappers { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("protocolMappers")]
  public List<ProtocolMapperRepresentation>? ProtocolMappers { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("components")]
  public MultivaluedHashMapStringComponentExportRepresentation? Components { get; set; }

  [JsonPropertyName("internationalizationEnabled")]
  public bool? InternationalizationEnabled { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("supportedLocales")]
  public List<string?>? SupportedLocales { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("defaultLocale")]
  public string? DefaultLocale { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("authenticationFlows")]
  public List<AuthenticationFlowRepresentation>? AuthenticationFlows { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("authenticatorConfig")]
  public List<AuthenticatorConfigRepresentation>? AuthenticatorConfig { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("requiredActions")]
  public List<RequiredActionProviderRepresentation>? RequiredActions { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("browserFlow")]
  public string? BrowserFlow { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("registrationFlow")]
  public string? RegistrationFlow { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("directGrantFlow")]
  public string? DirectGrantFlow { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("resetCredentialsFlow")]
  public string? ResetCredentialsFlow { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("clientAuthenticationFlow")]
  public string? ClientAuthenticationFlow { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("dockerAuthenticationFlow")]
  public string? DockerAuthenticationFlow { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("firstBrokerLoginFlow")]
  public string? FirstBrokerLoginFlow { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("attributes")]
  public Dictionary<string, string?>? Attributes { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("keycloakVersion")]
  public string? KeycloakVersion { get; set; }

  [JsonPropertyName("userManagedAccessAllowed")]
  public bool? UserManagedAccessAllowed { get; set; }

  [JsonPropertyName("organizationsEnabled")]
  public bool? OrganizationsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("organizations")]
  public List<OrganizationRepresentation>? Organizations { get; set; }

  [JsonPropertyName("verifiableCredentialsEnabled")]
  public bool? VerifiableCredentialsEnabled { get; set; }

  [JsonPropertyName("adminPermissionsEnabled")]
  public bool? AdminPermissionsEnabled { get; set; }

  [JsonPropertyName("social")]
  public bool? Social { get; set; }

  [JsonPropertyName("updateProfileOnInitialSocialLogin")]
  public bool? UpdateProfileOnInitialSocialLogin { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("socialProviders")]
  public Dictionary<string, string?>? SocialProviders { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("applicationScopeMappings")]
  public Dictionary<string, List<ScopeMappingRepresentation>?>? ApplicationScopeMappings { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("applications")]
  public List<ApplicationRepresentation>? Applications { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("oauthClients")]
  public List<OAuthClientRepresentation>? OauthClients { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("clientTemplates")]
  public List<ClientTemplateRepresentation>? ClientTemplates { get; set; }

}
