//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// RealmRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/RealmRepresentation
/// </summary>
public class RealmRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("realm")]
  public string? Realm { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("displayName")]
  public string? DisplayName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("displayNameHtml")]
  public string? DisplayNameHtml { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("notBefore")]
  public int? NotBefore { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("defaultSignatureAlgorithm")]
  public string? DefaultSignatureAlgorithm { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("revokeRefreshToken")]
  public bool? RevokeRefreshToken { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("refreshTokenMaxReuse")]
  public int? RefreshTokenMaxReuse { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessTokenLifespan")]
  public int? AccessTokenLifespan { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessTokenLifespanForImplicitFlow")]
  public int? AccessTokenLifespanForImplicitFlow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ssoSessionIdleTimeout")]
  public int? SsoSessionIdleTimeout { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ssoSessionMaxLifespan")]
  public int? SsoSessionMaxLifespan { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ssoSessionIdleTimeoutRememberMe")]
  public int? SsoSessionIdleTimeoutRememberMe { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ssoSessionMaxLifespanRememberMe")]
  public int? SsoSessionMaxLifespanRememberMe { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("offlineSessionIdleTimeout")]
  public int? OfflineSessionIdleTimeout { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("offlineSessionMaxLifespanEnabled")]
  public bool? OfflineSessionMaxLifespanEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("offlineSessionMaxLifespan")]
  public int? OfflineSessionMaxLifespan { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientSessionIdleTimeout")]
  public int? ClientSessionIdleTimeout { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientSessionMaxLifespan")]
  public int? ClientSessionMaxLifespan { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientOfflineSessionIdleTimeout")]
  public int? ClientOfflineSessionIdleTimeout { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientOfflineSessionMaxLifespan")]
  public int? ClientOfflineSessionMaxLifespan { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessCodeLifespan")]
  public int? AccessCodeLifespan { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessCodeLifespanUserAction")]
  public int? AccessCodeLifespanUserAction { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accessCodeLifespanLogin")]
  public int? AccessCodeLifespanLogin { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("actionTokenGeneratedByAdminLifespan")]
  public int? ActionTokenGeneratedByAdminLifespan { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("actionTokenGeneratedByUserLifespan")]
  public int? ActionTokenGeneratedByUserLifespan { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("oauth2DeviceCodeLifespan")]
  public int? Oauth2DeviceCodeLifespan { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("oauth2DevicePollingInterval")]
  public int? Oauth2DevicePollingInterval { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("sslRequired")]
  public string? SslRequired { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("passwordCredentialGrantAllowed")]
  public bool? PasswordCredentialGrantAllowed { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("registrationAllowed")]
  public bool? RegistrationAllowed { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("registrationEmailAsUsername")]
  public bool? RegistrationEmailAsUsername { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rememberMe")]
  public bool? RememberMe { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("verifyEmail")]
  public bool? VerifyEmail { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("loginWithEmailAllowed")]
  public bool? LoginWithEmailAllowed { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("duplicateEmailsAllowed")]
  public bool? DuplicateEmailsAllowed { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resetPasswordAllowed")]
  public bool? ResetPasswordAllowed { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("editUsernameAllowed")]
  public bool? EditUsernameAllowed { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userCacheEnabled")]
  public bool? UserCacheEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("realmCacheEnabled")]
  public bool? RealmCacheEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("bruteForceProtected")]
  public bool? BruteForceProtected { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("permanentLockout")]
  public bool? PermanentLockout { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxTemporaryLockouts")]
  public int? MaxTemporaryLockouts { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("bruteForceStrategy")]
  public BruteForceStrategy? BruteForceStrategy { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxFailureWaitSeconds")]
  public int? MaxFailureWaitSeconds { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("minimumQuickLoginWaitSeconds")]
  public int? MinimumQuickLoginWaitSeconds { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("waitIncrementSeconds")]
  public int? WaitIncrementSeconds { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("quickLoginCheckMilliSeconds")]
  public long? QuickLoginCheckMilliSeconds { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("maxDeltaTimeSeconds")]
  public int? MaxDeltaTimeSeconds { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("failureFactor")]
  public int? FailureFactor { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("privateKey")]
  public string? PrivateKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("publicKey")]
  public string? PublicKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("certificate")]
  public string? Certificate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("codeSecret")]
  public string? CodeSecret { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("roles")]
  public RolesRepresentation? Roles { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("groups")]
  public List<GroupRepresentation>? Groups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("defaultRoles")]
  public List<string?>? DefaultRoles { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("defaultRole")]
  public RoleRepresentation? DefaultRole { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("adminPermissionsClient")]
  public ClientRepresentation? AdminPermissionsClient { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("defaultGroups")]
  public List<string?>? DefaultGroups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requiredCredentials")]
  public List<string?>? RequiredCredentials { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("passwordPolicy")]
  public string? PasswordPolicy { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("otpPolicyType")]
  public string? OtpPolicyType { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("otpPolicyAlgorithm")]
  public string? OtpPolicyAlgorithm { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("otpPolicyInitialCounter")]
  public int? OtpPolicyInitialCounter { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("otpPolicyDigits")]
  public int? OtpPolicyDigits { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("otpPolicyLookAheadWindow")]
  public int? OtpPolicyLookAheadWindow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("otpPolicyPeriod")]
  public int? OtpPolicyPeriod { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("otpPolicyCodeReusable")]
  public bool? OtpPolicyCodeReusable { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("otpSupportedApplications")]
  public List<string?>? OtpSupportedApplications { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("localizationTexts")]
  public Dictionary<string, Dictionary<string, string?>?>? LocalizationTexts { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyRpEntityName")]
  public string? WebAuthnPolicyRpEntityName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicySignatureAlgorithms")]
  public List<string?>? WebAuthnPolicySignatureAlgorithms { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyRpId")]
  public string? WebAuthnPolicyRpId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyAttestationConveyancePreference")]
  public string? WebAuthnPolicyAttestationConveyancePreference { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyAuthenticatorAttachment")]
  public string? WebAuthnPolicyAuthenticatorAttachment { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyRequireResidentKey")]
  public string? WebAuthnPolicyRequireResidentKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyUserVerificationRequirement")]
  public string? WebAuthnPolicyUserVerificationRequirement { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyCreateTimeout")]
  public int? WebAuthnPolicyCreateTimeout { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyAvoidSameAuthenticatorRegister")]
  public bool? WebAuthnPolicyAvoidSameAuthenticatorRegister { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyAcceptableAaguids")]
  public List<string?>? WebAuthnPolicyAcceptableAaguids { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyExtraOrigins")]
  public List<string?>? WebAuthnPolicyExtraOrigins { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyPasswordlessRpEntityName")]
  public string? WebAuthnPolicyPasswordlessRpEntityName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyPasswordlessSignatureAlgorithms")]
  public List<string?>? WebAuthnPolicyPasswordlessSignatureAlgorithms { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyPasswordlessRpId")]
  public string? WebAuthnPolicyPasswordlessRpId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyPasswordlessAttestationConveyancePreference")]
  public string? WebAuthnPolicyPasswordlessAttestationConveyancePreference { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyPasswordlessAuthenticatorAttachment")]
  public string? WebAuthnPolicyPasswordlessAuthenticatorAttachment { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyPasswordlessRequireResidentKey")]
  public string? WebAuthnPolicyPasswordlessRequireResidentKey { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyPasswordlessUserVerificationRequirement")]
  public string? WebAuthnPolicyPasswordlessUserVerificationRequirement { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyPasswordlessCreateTimeout")]
  public int? WebAuthnPolicyPasswordlessCreateTimeout { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister")]
  public bool? WebAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyPasswordlessAcceptableAaguids")]
  public List<string?>? WebAuthnPolicyPasswordlessAcceptableAaguids { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyPasswordlessExtraOrigins")]
  public List<string?>? WebAuthnPolicyPasswordlessExtraOrigins { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("webAuthnPolicyPasswordlessPasskeysEnabled")]
  public bool? WebAuthnPolicyPasswordlessPasskeysEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientProfiles")]
  public ClientProfilesRepresentation? ClientProfiles { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientPolicies")]
  public ClientPoliciesRepresentation? ClientPolicies { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("users")]
  public List<UserRepresentation>? Users { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("federatedUsers")]
  public List<UserRepresentation>? FederatedUsers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("scopeMappings")]
  public List<ScopeMappingRepresentation>? ScopeMappings { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientScopeMappings")]
  public Dictionary<string, List<ScopeMappingRepresentation>?>? ClientScopeMappings { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clients")]
  public List<ClientRepresentation>? Clients { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientScopes")]
  public List<ClientScopeRepresentation>? ClientScopes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("defaultDefaultClientScopes")]
  public List<string?>? DefaultDefaultClientScopes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("defaultOptionalClientScopes")]
  public List<string?>? DefaultOptionalClientScopes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("browserSecurityHeaders")]
  public Dictionary<string, string?>? BrowserSecurityHeaders { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("smtpServer")]
  public Dictionary<string, string?>? SmtpServer { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userFederationProviders")]
  public List<UserFederationProviderRepresentation>? UserFederationProviders { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userFederationMappers")]
  public List<UserFederationMapperRepresentation>? UserFederationMappers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("loginTheme")]
  public string? LoginTheme { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("accountTheme")]
  public string? AccountTheme { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("adminTheme")]
  public string? AdminTheme { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("emailTheme")]
  public string? EmailTheme { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("eventsEnabled")]
  public bool? EventsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("eventsExpiration")]
  public long? EventsExpiration { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("eventsListeners")]
  public List<string?>? EventsListeners { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabledEventTypes")]
  public List<string?>? EnabledEventTypes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("adminEventsEnabled")]
  public bool? AdminEventsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("adminEventsDetailsEnabled")]
  public bool? AdminEventsDetailsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("identityProviders")]
  public List<IdentityProviderRepresentation>? IdentityProviders { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("identityProviderMappers")]
  public List<IdentityProviderMapperRepresentation>? IdentityProviderMappers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("protocolMappers")]
  public List<ProtocolMapperRepresentation>? ProtocolMappers { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("components")]
  public MultivaluedHashMapStringComponentExportRepresentation? Components { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("internationalizationEnabled")]
  public bool? InternationalizationEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("supportedLocales")]
  public List<string?>? SupportedLocales { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("defaultLocale")]
  public string? DefaultLocale { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authenticationFlows")]
  public List<AuthenticationFlowRepresentation>? AuthenticationFlows { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authenticatorConfig")]
  public List<AuthenticatorConfigRepresentation>? AuthenticatorConfig { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requiredActions")]
  public List<RequiredActionProviderRepresentation>? RequiredActions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("browserFlow")]
  public string? BrowserFlow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("registrationFlow")]
  public string? RegistrationFlow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("directGrantFlow")]
  public string? DirectGrantFlow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resetCredentialsFlow")]
  public string? ResetCredentialsFlow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientAuthenticationFlow")]
  public string? ClientAuthenticationFlow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("dockerAuthenticationFlow")]
  public string? DockerAuthenticationFlow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("firstBrokerLoginFlow")]
  public string? FirstBrokerLoginFlow { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("attributes")]
  public Dictionary<string, string?>? Attributes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("keycloakVersion")]
  public string? KeycloakVersion { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userManagedAccessAllowed")]
  public bool? UserManagedAccessAllowed { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizationsEnabled")]
  public bool? OrganizationsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("organizations")]
  public List<OrganizationRepresentation>? Organizations { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("verifiableCredentialsEnabled")]
  public bool? VerifiableCredentialsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("adminPermissionsEnabled")]
  public bool? AdminPermissionsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("social")]
  public bool? Social { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("updateProfileOnInitialSocialLogin")]
  public bool? UpdateProfileOnInitialSocialLogin { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("socialProviders")]
  public Dictionary<string, string?>? SocialProviders { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("applicationScopeMappings")]
  public Dictionary<string, List<ScopeMappingRepresentation>?>? ApplicationScopeMappings { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("applications")]
  public List<ApplicationRepresentation>? Applications { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("oauthClients")]
  public List<OAuthClientRepresentation>? OauthClients { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientTemplates")]
  public List<ClientTemplateRepresentation>? ClientTemplates { get; set; }
}
