//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// RealmEventsConfigRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/RealmEventsConfigRepresentation
/// </summary>
public class RealmEventsConfigRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("eventsEnabled")]
  public bool? EventsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("eventsExpiration")]
  public long? EventsExpiration { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("eventsListeners")]
  public List<string?>? EventsListeners { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabledEventTypes")]
  public List<string?>? EnabledEventTypes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("adminEventsEnabled")]
  public bool? AdminEventsEnabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("adminEventsDetailsEnabled")]
  public bool? AdminEventsDetailsEnabled { get; set; }
}
