//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// Response model for ResourceRepresentation
/// </summary>
public class ResourceRepresentation
{
  [JsonPropertyName("_id")]
  public string? Id { get; set; }

  [JsonPropertyName("name")]
  public string? Name { get; set; }

  [JsonPropertyName("uris")]
  public List<string?>? Uris { get; set; }

  [JsonPropertyName("type")]
  public string? Type { get; set; }

  [JsonPropertyName("scopes")]
  public List<ScopeRepresentation>? Scopes { get; set; }

  [JsonPropertyName("icon_uri")]
  public string? IconUri { get; set; }

  [JsonPropertyName("owner")]
  public ResourceOwnerRepresentation? Owner { get; set; }

  [JsonPropertyName("ownerManagedAccess")]
  public bool? OwnerManagedAccess { get; set; }

  [JsonPropertyName("displayName")]
  public string? DisplayName { get; set; }

  [JsonPropertyName("attributes")]
  public Dictionary<string, List<string?>?>? Attributes { get; set; }

  [JsonPropertyName("scopesUma")]
  public List<ScopeRepresentation>? ScopesUma { get; set; }

}
