//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// ResourceServerRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/ResourceServerRepresentation
/// </summary>
public class ResourceServerRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientId")]
  public string? ClientId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("allowRemoteResourceManagement")]
  public bool? AllowRemoteResourceManagement { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("policyEnforcementMode")]
  public PolicyEnforcementMode? PolicyEnforcementMode { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("resources")]
  public List<ResourceRepresentation>? Resources { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("policies")]
  public List<PolicyRepresentation>? Policies { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("scopes")]
  public List<ScopeRepresentation>? Scopes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("decisionStrategy")]
  public DecisionStrategy? DecisionStrategy { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("authorizationSchema")]
  public AuthorizationSchema? AuthorizationSchema { get; set; }
}
