//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// RolesRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/RolesRepresentation
/// </summary>
public class RolesRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("realm")]
  public List<RoleRepresentation>? Realm { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("client")]
  public Dictionary<string, List<RoleRepresentation>?>? Client { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("application")]
  public Dictionary<string, List<RoleRepresentation>?>? Application { get; set; }
}
