//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// RoleRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/RoleRepresentation
/// </summary>
public class RoleRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("description")]
  public string? Description { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("scopeParamRequired")]
  public bool? ScopeParamRequired { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("composite")]
  public bool? Composite { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("composites")]
  public Composites? Composites { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientRole")]
  public bool? ClientRole { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("containerId")]
  public string? ContainerId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("attributes")]
  public Dictionary<string, List<string?>?>? Attributes { get; set; }
}
