//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// ScopeMappingRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/ScopeMappingRepresentation
/// </summary>
public class ScopeMappingRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("self")]
  public string? Self { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("client")]
  public string? Client { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientTemplate")]
  public string? ClientTemplate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientScope")]
  public string? ClientScope { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("roles")]
  public List<string?>? Roles { get; set; }
}
