//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// SocialLinkRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/SocialLinkRepresentation
/// </summary>
public class SocialLinkRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("socialProvider")]
  public string? SocialProvider { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("socialUserId")]
  public string? SocialUserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("socialUsername")]
  public string? SocialUsername { get; set; }
}
