//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// UPGroup from OpenAPI schema.
/// Schema path: #/components/schemas/UPGroup
/// </summary>
public class UPGroup
{
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("displayHeader")]
  public string? DisplayHeader { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("displayDescription")]
  public string? DisplayDescription { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("annotations")]
  public Dictionary<string, object?>? Annotations { get; set; }
}
