//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// UserRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/UserRepresentation
/// </summary>
public class UserRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("firstName")]
  public string? FirstName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("lastName")]
  public string? LastName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("email")]
  public string? Email { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("emailVerified")]
  public bool? EmailVerified { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("attributes")]
  public Dictionary<string, List<string?>?>? Attributes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userProfileMetadata")]
  public UserProfileMetadata? UserProfileMetadata { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("self")]
  public string? Self { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("origin")]
  public string? Origin { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("createdTimestamp")]
  public long? CreatedTimestamp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("totp")]
  public bool? Totp { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("federationLink")]
  public string? FederationLink { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("serviceAccountClientId")]
  public string? ServiceAccountClientId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("credentials")]
  public List<CredentialRepresentation>? Credentials { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("disableableCredentialTypes")]
  public List<string?>? DisableableCredentialTypes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("requiredActions")]
  public List<string?>? RequiredActions { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("federatedIdentities")]
  public List<FederatedIdentityRepresentation>? FederatedIdentities { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("realmRoles")]
  public List<string?>? RealmRoles { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientRoles")]
  public Dictionary<string, List<string?>?>? ClientRoles { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientConsents")]
  public List<UserConsentRepresentation>? ClientConsents { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("notBefore")]
  public int? NotBefore { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("applicationRoles")]
  public Dictionary<string, List<string?>?>? ApplicationRoles { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("socialLinks")]
  public List<SocialLinkRepresentation>? SocialLinks { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("groups")]
  public List<string?>? Groups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("access")]
  public Dictionary<string, bool>? Access { get; set; }
}
