//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// UserSessionRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/UserSessionRepresentation
/// </summary>
public class UserSessionRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("username")]
  public string? Username { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("userId")]
  public string? UserId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("ipAddress")]
  public string? IpAddress { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("start")]
  public long? Start { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("lastAccess")]
  public long? LastAccess { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("rememberMe")]
  public bool? RememberMe { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clients")]
  public Dictionary<string, string?>? Clients { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("transientUser")]
  public bool? TransientUser { get; set; }
}
