//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// UserProfileAttributeMetadata from OpenAPI schema.
/// Schema path: #/components/schemas/UserProfileAttributeMetadata
/// </summary>
public class UserProfileAttributeMetadata
{
  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("displayName")]
  public string? DisplayName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("required")]
  public bool? Required { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("readOnly")]
  public bool? ReadOnly { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("annotations")]
  public Dictionary<string, object?>? Annotations { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("validators")]
  public Dictionary<string, Dictionary<string, object?>?>? Validators { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("group")]
  public string? Group { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("multivalued")]
  public bool? Multivalued { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("defaultValue")]
  public string? DefaultValue { get; set; }
}
