//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// UserConsentRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/UserConsentRepresentation
/// </summary>
public class UserConsentRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("clientId")]
  public string? ClientId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("grantedClientScopes")]
  public List<string?>? GrantedClientScopes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("createdDate")]
  public long? CreatedDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("lastUpdatedDate")]
  public long? LastUpdatedDate { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("grantedRealmRoles")]
  public List<string?>? GrantedRealmRoles { get; set; }
}
