//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// UPConfig from OpenAPI schema.
/// Schema path: #/components/schemas/UPConfig
/// </summary>
public class UserProfileConfig
{
  [System.Text.Json.Serialization.JsonPropertyName("attributes")]
  public List<UPAttribute>? Attributes { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("groups")]
  public List<UPGroup>? Groups { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("unmanagedAttributePolicy")]
  public UnmanagedAttributePolicy? UnmanagedAttributePolicy { get; set; }
}
