//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// UserFederationProviderRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/UserFederationProviderRepresentation
/// </summary>
public class UserFederationProviderRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("displayName")]
  public string? DisplayName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("providerName")]
  public string? ProviderName { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("config")]
  public Dictionary<string, string?>? Config { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("priority")]
  public int? Priority { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("fullSyncPeriod")]
  public int? FullSyncPeriod { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("changedSyncPeriod")]
  public int? ChangedSyncPeriod { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("lastSync")]
  public int? LastSync { get; set; }
}
