//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// VerifiableCredentialOfferActionConfig from OpenAPI schema.
/// Schema path: #/components/schemas/VerifiableCredentialOfferActionConfig
/// </summary>
public partial class VerifiableCredentialOfferActionConfig
{
  [System.Text.Json.Serialization.JsonPropertyName("credentialConfigurationId")]
  public string? CredentialConfigurationId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("clientId")]
  public string? ClientId { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("preAuthorized")]
  public bool? PreAuthorized { get; set; }
}
