//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// WorkflowRepresentation from OpenAPI schema.
/// Schema path: #/components/schemas/WorkflowRepresentation
/// </summary>
public class WorkflowRepresentation
{
  [System.Text.Json.Serialization.JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("name")]
  public string? Name { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("on")]
  public string? On { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("schedule")]
  public WorkflowScheduleRepresentation? Schedule { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("concurrency")]
  public WorkflowConcurrencyRepresentation? Concurrency { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("if")]
  public string? If { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("steps")]
  public List<WorkflowStepRepresentation>? Steps { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("state")]
  public WorkflowStateRepresentation? State { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("with")]
  public MultivaluedHashMapStringString? With { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("cancelInProgress")]
  public string? CancelInProgress { get; set; }

  [System.Text.Json.Serialization.JsonPropertyName("restartInProgress")]
  public string? RestartInProgress { get; set; }
}
