//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

#nullable enable

namespace Apigen.Keycloak.Admin.Models;

/// <summary>
/// Request model for WorkflowRepresentation
/// </summary>
public class WorkflowRepresentationRequest
{
  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("id")]
  public string? Id { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("name")]
  public string? Name { get; set; }

  [JsonPropertyName("enabled")]
  public bool? Enabled { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("on")]
  public string? On { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("schedule")]
  public WorkflowScheduleRepresentation? Schedule { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("concurrency")]
  public WorkflowConcurrencyRepresentation? Concurrency { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("if")]
  public string? If { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("steps")]
  public List<WorkflowStepRepresentation>? Steps { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("state")]
  public WorkflowStateRepresentation? State { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("with")]
  public MultivaluedHashMapStringString? With { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("cancelInProgress")]
  public string? CancelInProgress { get; set; }

  [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
  [JsonPropertyName("restartInProgress")]
  public string? RestartInProgress { get; set; }

}
