//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Keycloak.Admin.Client;

/// <summary>
/// Request parameters for 
/// Operation: GET /admin/realms/{realm}/components
/// </summary>
public partial class GetComponentRequest : BaseRequest
{
  /// <summary>
  /// name
  /// </summary>
  [JsonPropertyName("name")]
  public string? Name { get; set; }

  /// <summary>
  /// parent
  /// </summary>
  [JsonPropertyName("parent")]
  public string? Parent { get; set; }

  /// <summary>
  /// providerId
  /// </summary>
  [JsonPropertyName("providerId")]
  public string? ProviderId { get; set; }

  /// <summary>
  /// type
  /// </summary>
  [JsonPropertyName("type")]
  public string? Type { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (Name != null)
      queryParams["name"] = Name;
    if (Parent != null)
      queryParams["parent"] = Parent;
    if (ProviderId != null)
      queryParams["providerId"] = ProviderId;
    if (Type != null)
      queryParams["type"] = Type;

    return queryParams.ToQueryString();
  }
}
