//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Keycloak.Admin.Client;

/// <summary>
/// Request parameters for Partial export of existing realm into a JSON file.
/// Operation: POST /admin/realms/{realm}/partial-export
/// </summary>
public partial class PostRealmsAdminRequest : BaseRequest
{
  /// <summary>
  /// exportClients
  /// </summary>
  [JsonPropertyName("exportClients")]
  public bool? ExportClients { get; set; }

  /// <summary>
  /// exportGroupsAndRoles
  /// </summary>
  [JsonPropertyName("exportGroupsAndRoles")]
  public bool? ExportGroupsAndRoles { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (ExportClients != null)
      queryParams["exportClients"] = ExportClients;
    if (ExportGroupsAndRoles != null)
      queryParams["exportGroupsAndRoles"] = ExportGroupsAndRoles;

    return queryParams.ToQueryString();
  }
}
