//
// <auto-generated>
// Keycloak Admin REST API Models - Auto-generated from OpenAPI specification
//
// Generated by: ApiGenerator
// Source: specs/keycloak.yaml
// API: Keycloak Admin REST API
// Version: 1.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Web;

#nullable enable

namespace Apigen.Keycloak.Admin.Client;

/// <summary>
/// Request parameters for Migrate scheduled resources from one step to another
/// Operation: POST /admin/realms/{realm}/workflows/migrate
/// </summary>
public partial class PostWorkflowsRequest : BaseRequest
{
  /// <summary>
  /// A String representing the id of the step to migrate from
  /// </summary>
  [JsonPropertyName("from")]
  public string? From { get; set; }

  /// <summary>
  /// A String representing the id of the step to migrate to
  /// </summary>
  [JsonPropertyName("to")]
  public string? To { get; set; }

  public override string ToQueryString()
  {
    Dictionary<string, object> queryParams = new Dictionary<string, object>();

    if (From != null)
      queryParams["from"] = From;
    if (To != null)
      queryParams["to"] = To;

    return queryParams.ToQueryString();
  }
}
